### ISSUE TITLE
Code does not build

### ISSUE THREAD

**Issue by funat** [jjxtra/ExchangeSharp#10]
I have a  problem building the code upon checkout. 

Details:
I get 52 errors. Mostly basic syntax errors such as undeclared variables. Building in VS 2015 against .NET 4.5 and .NET 4.6. 

For example in BaseAPI.cs

protected bool ReadCache<T>(string key, out T value)
        {
            lock (cache)
            {
                if (cache.TryGetValue(key, out KeyValuePair<DateTime, object> cacheValue))
                {
                    // if not expired, return
                    if (cacheValue.Key > DateTime.UtcNow)
                    {
                        value = (T)cacheValue.Value;
                        return true;
                    }
                    cache.Remove(key);
                }
            }
            value = default(T);
            return false;
        }

cacheValue is not defined. 

Am I missing something?

**Comment by jjxtra** [comment]
Use VS 2017

Jeff Johnson
CEO / CTO, Digital Ruby, LLC

**Comment by funat** [comment]
Ok, I will try. 
Just a short question - is there a reason for not using ConcurrentDictionary for the cache implementation in the BaseAPI?

**Comment by jjxtra** [comment]
ConcurrentDictionary would certainly work, but underneath it is using the same lock mechanism that I have, so it's probably not worth migrating at this point.
