### ISSUE TITLE
Sealed Classes?

### ISSUE THREAD

**Issue by BobDeCuir** [jjxtra/ExchangeSharp#100]
The latest update now has all the ExchangeAPI based classes sealed. I've been extending these classes with my own Interface to add functionality needed in my app. They're now broken because I can't derive from them anymore. 

Would it be possible to unseal these classes? 

I can get around it by creating these extended classes with the ExchangeAPI passed as a parameter if not. At the moment, however, I can't compile.

**Comment by jjxtra** [comment]
I would highly recommend extension methods - unless you are overriding one
of the protected methods?

Jeff Johnson
CEO / CTO, Digital Ruby, LLC

**Comment by BobDeCuir** [comment]
Good suggestion, and I can do that. It'll be a bit of rework though. I do recognize the benefit of sealing these classes.
