### ISSUE TITLE
How to stop GetTickersWebSocket?

### ISSUE THREAD

**Issue by wukan1986** [jjxtra/ExchangeSharp#102]
Hi, 
How to stop receive from GetTickersWebSocket?
I use socket.Dispose(),but it wait forever.

**Comment by wukan1986** [comment]
public static void Main(string[] args)
{
	// create a web socket connection to Binance. Note you can Dispose the socket anytime to shut it down.
	// the web socket will handle disconnects and attempt to re-connect automatically.
	ExchangeBinanceAPI b = new ExchangeBinanceAPI();
	var socket = b.GetTickersWebSocket((tickers) =>
	{
		Console.WriteLine("{0} tickers, first: {1}", tickers.Count, tickers.First());
	});

	{
		Console.WriteLine("Press ENTER to shutdown.");
		Console.ReadLine();
		socket.Dispose();
		Console.WriteLine("Press ENTER to shutdown.");
		Console.ReadLine();
	}
}

**Comment by jjxtra** [comment]
Fixed in latest master
