### ISSUE TITLE
[FEATURE REQUEST]change interface request

### ISSUE THREAD

**Issue by wukan1986** [jjxtra/ExchangeSharp#104]
Hi, 
Thank you for your work.

I think change code
```
OnCancelOrderAsync(string orderId)
OnGetOrderDetailsAsync(string orderId)
```
to 
```
OnCancelOrderAsync(string orderId, string symbol = null)
OnGetOrderDetailsAsync(string orderId, string symbol = null)
```

is better for Binance API.

**Comment by jjxtra** [comment]
Not needed, the orderId param can be ORDERID,SYMBOLID. Binance is the only API with this crappy behavior, don't want to add this param for other API.

**Comment by wukan1986** [comment]
the Okex is same as Binance, must use symbol.
maybe some exchange different symbol will get same orderId.

for example ,the https://github.com/ccxt/ccxt 
`def fetch_order(self, id, symbol=None, params={}):`

**Comment by jjxtra** [comment]
Hmmm, ok I wish the exchanges did not do this, seems like very poor design. They must be re-using order id for each symbol. Ok, let's add the symbol parameter. As long as it defaults to null, should be fine. Can you do a pull request for Binance and Okex?

**Comment by wukan1986** [comment]
OK, i will do it

**Comment by jjxtra** [comment]
This has been merged in.
