### ISSUE TITLE
How to get Monthly candles ?

### ISSUE THREAD

**Issue by zanek** [jjxtra/ExchangeSharp#11]
How does one get Monthly candles, since the number of seconds per month varies ?

**Comment by jjxtra** [comment]
It is API dependant, but there is a magic seconds value that approximates one month: CryptoUtility.SecondsToPeriodString(periodSeconds)

**Comment by zanek** [comment]
Thanks JJXTRA,   I love your library and coding style so far.

 Also, how does one get the list of all symbols from a given exchange ? Looks like Kraken has a special symbol list

**Comment by jjxtra** [comment]
GetSymbols
