### ISSUE TITLE
[FEATURE REQUEST] Could you support subscription of some specific symbols for GetTickersWebSocket()

### ISSUE THREAD

**Issue by ctguxp** [jjxtra/ExchangeSharp#116]
I have a [FEATURE REQUEST]

Details:

Could you change the interface from 
IDisposable GetTickersWebSocket(System.Action<IReadOnlyCollection<KeyValuePair<string, ExchangeTicker>>> tickers);

to
IDisposable GetTickersWebSocket(System.Action<IReadOnlyCollection<KeyValuePair<string, ExchangeTicker>>> tickers, IList<string> symbols = null);

so, I can subscribe some specific symbols for market data using websocket method, But I don't want subscribe all symbols include some unused symbols. I have check the exchange API documents, most of them supports this usage, so could you support that.

**Comment by wukan1986** [comment]
maybe need subscribe and unsubscribe functions

**Comment by jjxtra** [comment]
Happy with the change, but let's make it params string[] symbols = null. Send a pull request and I will look it over.

**Comment by jjxtra** [comment]
The method call subscribes and returns IDisposable, which when disposed unsubscribes.
