### ISSUE TITLE
Balance - total amount and locked amount

### ISSUE THREAD

**Issue by droiduser1982** [jjxtra/ExchangeSharp#117]
I'm using the binance exchange.

There are two methods to charge balance:
- GetAmounts
- GetAmountsAvailableToTrade

I need to know my locked amount and my total amount. 

With these two methods I get it separately, but I have to make two calls to the API.

It would be nice to be able to make a single call and get the total amount of BNB and the amount locked

I think that in the rest of the exchanges this is the same

thanks

**Comment by jjxtra** [comment]
Not all exchanges provide this. If you want to make a third overload that does both in one shot, feel free to submit a pull request.
