### ISSUE TITLE
Timezone for Exchanges must be UTC

### ISSUE THREAD

**Issue by LORDofDOOM** [jjxtra/ExchangeSharp#121]
I have a [BUG REPORT]

Details:

Exchanges return DateTimeKind.Unspecified for e.g. OnGetCandlesAsync - That's IMHO wrong because all DateTime values should be UTC. 

If I use .ToUniversalTime(), on DateTimeKind.Unspecified (this is already UTC on most exchanges, but C# don't know about it) this function will subtract 2 hours if you are in GMT Timezone. In this case all candles are wrong (2 hours to early)

This is important to analyze charts from candles and create actions from this.

**Comment by jjxtra** [comment]
Latest commit in master resolves this problem. Please let me know if it solves your use case.

**Comment by LORDofDOOM** [comment]
Thank you very much -> Looks good - I test it against my database :-)
