### ISSUE TITLE
Livecoin 

### ISSUE THREAD

**Issue by pixel75** [jjxtra/ExchangeSharp#123]
I have a [BUG REPORT]

Details:
I'm testing the PlaceOrder on Livecon
            livecoinAPI.LoadAPIKeysUnsecure("pub", "priv");
            ExchangeOrderResult result = livecoinAPI.PlaceOrder(new ExchangeOrderRequest
            {
                Amount = 0.01m,
                IsBuy = false, //false = sell, true = buy
                Price = 20000,
                Symbol = "BTC/USD"
            });

function fail with this error message:
**ExchangeSharp.APIException: 'Request is missing required form field 'currencyPair''**

URI is well formed: **https://api.livecoin.net/exchange/selllimit?currencyPair=BTC/USD&price=20000&quantity=0,01**

any ideas?

**Comment by pixel75** [comment]
Same error with this call:
 ExchangeOrderResult result = livecoinAPI.PlaceOrder(new ExchangeOrderRequest
            {
                Amount = 0.01m,
                IsBuy = false, //false = sell, true = buy
                Price = 20000,
                Symbol = "BTC_USD"
            });

**Comment by jjxtra** [comment]
Let me know if you find anything with this. I don't have a livecoin account.

**Comment by jjxtra** [comment]
Checked in some code, try it again

**Comment by jjxtra** [comment]
Please open a new issue if this doesn't work for you now.
