### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by jacobdeboer33** [jjxtra/ExchangeSharp#13]
I have a question about ExchangeSharp.

Details:
I started using the binance api via ExchangeSharp. Before I got this working I needed to change my date time settings to sync with internet time. This worked after I changed this settings. But I now often still get exceptions when calling the api. What can I do to improve this, because this is very frustratring. My date time settings (in Windows 10) are set to automatic. I've chosen time.windows.com in Internet time settings to sync with.

And thank you for your time and effort you are putting in this project.

Jacob

Error Logs (if any):
ExchangeSharp.APIException: {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
   bij ExchangeSharp.BaseAPI.MakeRequest(String url, String baseUrl, Dictionary`2 payload, String method) in C:\Source\BittrexTrader\ExchangeSharp\API\BaseAPI.cs:regel 176
   bij ExchangeSharp.BaseAPI.MakeJsonRequest[T](String url, String baseUrl, Dictionary`2 payload, String requestMethod) in C:\Source\BittrexTrader\ExchangeSharp\API\BaseAPI.cs:regel 206
   bij ExchangeSharp.ExchangeBinanceAPI.GetAmounts() in C:\Source\BittrexTrader\ExchangeSharp\API\Exchanges\ExchangeBinanceAPI.cs:regel 57
   bij BittrexTrader.Algorithm.BittrexTrader.UpdateBalances() in C:\Source\BittrexTrader\BittrexTrader\Algorithm\BittrexTrader.cs:regel 677
   bij BittrexTrader.Algorithm.BittrexTrader.GetMarketsAndBalances() in C:\Source\BittrexTrader\BittrexTrader\Algorithm\BittrexTrader.cs:regel 384
   bij BittrexTrader.Algorithm.BittrexTrader.Start(Decimal buyPart, Decimal sellPercentageOffset, Decimal buyPercentageOffset, Decimal historyTake

The more information you can provide, the better :)

**Comment by jjxtra** [comment]
Changed rcvWindow to 1 minute default, try it again with latest code
