### ISSUE TITLE
Adding GetTickersAsync to OKEX

### ISSUE THREAD

**Issue by sthewissen** [jjxtra/ExchangeSharp#130]
@wukan1986 Noticed you created the OKEX integration, however it lacks a GetTickersAsync. Perhaps this endpoint could be used for that?

https://www.okex.com/v2/spot/markets/index-tickers?limit=100000000

I tried adding it myself but am running into some issues testing it.

**Comment by jjxtra** [comment]
It has been checked in. Donations are always appreciated.
