### ISSUE TITLE
Poloniex new order Error

### ISSUE THREAD

**Issue by ivanKo123** [jjxtra/ExchangeSharp#133]
I have a BUG REPORT
Hi,I have a problem using c # I try to submit an order - it gives an error
Details:
ExchangePoloniexAPI ExchangePoloniexAPI = new ExchangePoloniexAPI();
           
             ExchangePoloniexAPI.LoadAPIKeysUnsecure(ApiKeys.PublicKey, ApiKeys.PrivateKey);
             ExchangeOrderRequest orderRequest = new ExchangeOrderRequest();

            orderRequest.Amount = 0.00000001m;
             orderRequest.IsBuy = true;
             orderRequest.OrderType = OrderType.Market;
             orderRequest.Symbol = "BTC_ETH";
            // orderRequest.Price = (decimal)0.08378000;
            ExchangeOrderResult result = ExchangePoloniexAPI.PlaceOrder(orderRequest);  // <== ERROR "the specified method is not supported"

            //  ExchangeOrderResult result = await ExchangePoloniexAPI.PlaceOrderAsync(orderRequest); // <== ERROR "the specified method is not supported"

**Comment by bichuga** [comment]
Maybe market orders aren't supported at polo?

**Comment by jjxtra** [comment]
Please use the new PlaceSafeMarketOrderAsync call
