### ISSUE TITLE
Kraken 

### ISSUE THREAD

**Issue by pixel75** [jjxtra/ExchangeSharp#136]
I have a [BUG REPORT] 

Details:
OnGetAmountsAvailableToTradeAsync doesent work to me on Kraken.
so I modify the code as belove:

protected override async Task<Dictionary<string, decimal>> OnGetAmountsAvailableToTradeAsync()
 {
            string url = "/0/private/Balance";
            var payload = GetNoncePayload();
            JObject responseObject = await MakeJsonRequestAsync<JObject>(url, null, payload, "POST");
            CheckError(responseObject);
            Dictionary<string, decimal> balances =Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, decimal>>(responseObject["result"].ToString());
            return balances;
        }
on ExchangeKrakenAPI.cs

**Comment by jjxtra** [comment]
Use GetAmounts, amounts available to trade is not supported on Kraken
