### ISSUE TITLE
[FEATURE REQUEST]change ConnectWebSocket messageCallback

### ISSUE THREAD

**Issue by wukan1986** [jjxtra/ExchangeSharp#139]
I have a [FEATURE REQUEST]

I want to implement GetOrderBookWebSocket for Huobi.
But the data from it is compressed use GZip.

I try to decompress that in ExchangeHuobi.cs.
I use Encoding.UTF8.GetBytes to get the raw data.
but it's changed.
A = Encoding.UTF8.GetBytes(Encoding.UTF8.GetString(B,0,B.Length))
the A is not same as B.

so I suggest that modify the 
`ConnectWebSocket(string url, System.Action<string, WebSocketWrapper> messageCallback, System.Action<WebSocketWrapper> connectCallback = null) `
to
`ConnectWebSocket(string url, System.Action<byte[], WebSocketWrapper> messageCallback, System.Action<WebSocketWrapper> connectCallback = null)`
or
`ConnectWebSocket(string url, System.Action<string, byte[], WebSocketWrapper> messageCallback, System.Action<WebSocketWrapper> connectCallback = null)`

**Comment by jjxtra** [comment]
I checked in a change to just use byte[], no need to use both and create double the overhead.
