### ISSUE TITLE
SimplePeakValleyTrader

### ISSUE THREAD

**Issue by jacobdeboer33** [jjxtra/ExchangeSharp#14]
I have a Quaestion

I want to test out and use the SimplePeakValleyTrader that's in your code. I have a few questions. 
Am I right to say that this trader is not written for every market? The Update amounts function is getting the BTC and USD balances, while it maybe would be better if the base currency and market currency would be retrieved. 

Is it possible to create helper functions for all APIs that retrieve the base currency and market currency of a symbol? For example Bittrex uses the following notation: BTC-LTC and Binance uses LTCBTC. It would come in handy if there was a helper function on every API implementation to get the base and amrket currency of the symbol. (in this case BTC is basecurrency and LTC is marketcurrency)

Do you have any tips on what interval I have to begin testing? Minute(s), Hour(s)? 

How can I initiate the TradeInfo property? It cannot be set.

Thank you for your answers.
Jacob

**Comment by jjxtra** [comment]
Please only open issues for bugs or feature requests, thanks!
