### ISSUE TITLE
binance web socket problem

### ISSUE THREAD

**Issue by kamelmansouri** [jjxtra/ExchangeSharp#142]
![image](https://user-images.githubusercontent.com/11912880/40274004-0cf35956-5bc4-11e8-908d-d36d176e1019.png)

**Comment by jjxtra** [comment]
What Windows/Linux are you on?

**Comment by jjxtra** [comment]
https://stackoverflow.com/questions/45739625/system-platformnotsupportexception-the-websocket-protocol-is-not-supported-on-t?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by kamelmansouri** [comment]
I used windows 7 sp1 64bits.
After i used windows server 2012 ono problem ,websocket  work fine.

**Comment by jjxtra** [comment]
No plans to support Windows 7, I would suggest forking the repo for your purposes.
