### ISSUE TITLE
WriteToRequest UTF8 encoding confuses Polo signature validation

### ISSUE THREAD

**Issue by bichuga** [jjxtra/ExchangeSharp#153]
Commit 53fc836de9c5c597e0efd4957605af21e44309b2 change of encoding in BaseAPI.WriteToRequest from ASCII to UTF8 breaks Poloniex signing. (No idea why)

Was this change to fix a different issue?

**Comment by jjxtra** [comment]
Checked in a change with utf-8 without prefix bytes and verified Poloniex private API. Let me know if you see any issues.
