### ISSUE TITLE
Connecting too many websockets simultaneously fails silently

### ISSUE THREAD

**Issue by bichuga** [jjxtra/ExchangeSharp#155]
If I connect too many websockets simultaneously, only 5 of them actually get connected. In this code below, I only see 5 HTTPS requests. If I add a Task.Delay(1000) between each TrackMarketDepth call, all 100 get connected.

```
        private static void RunBinance()
        {
            this.binance = new ExchangeBinanceAPI();

            var syms = this.binance.GetSymbols();
            foreach (var sym in syms.Take(100))
            {
                this.TrackMarketDepth(sym);
            }

            Task.Delay(Int32.MaxValue).Wait();
        }

        public void TrackMarketDepth(string ticker)
        {
            void Callback(ExchangeSequencedWebsocketMessage<ExchangeOrderBook> book)
            {
                Log.Info($"Found order book to process for {ticker}");
            }

            Log.Info($"Attaching socket to {ticker}");
            this.binance.GetOrderBookWebSocket(ticker, Callback);
        }

```

![image](https://user-images.githubusercontent.com/9372553/40598299-b7995008-61fb-11e8-96cb-b0999f0e9ede.png)

**Comment by bichuga** [comment]
This is the root cause:
https://stackoverflow.com/questions/1361771/max-number-of-concurrent-httpwebrequests

Can you think of a clever way to buffer up websocket connections to be made?

**Comment by jjxtra** [comment]
Is there no way to get the order book for all symbols in one web socket?

Jeff Johnson
CEO / CTO, Digital Ruby, LLC

**Comment by bichuga** [comment]
Oh, good point! I'll try

**Comment by bichuga** [comment]
Yes this definitely works. Just gotta figure out how to not make this eat all my CPU.

![image](https://user-images.githubusercontent.com/9372553/40624732-294b4e24-6263-11e8-9b2c-8add056460b3.png)

**Comment by jjxtra** [comment]
Is that all newtonsoft? Maybe we can scan the string manually and look for the symbol without giving it to json so it can be discarded without the parsing overhead.
