### ISSUE TITLE
TickersWebSocket doesn't work!

### ISSUE THREAD

**Issue by Tolik7** [jjxtra/ExchangeSharp#158]
I have updated my project and it was broken!
I used TickersWebSocket function like as 
My code
 socketBittrex = clientBittrex.GetTickersWebSocket(freshTickers =>
            {
                foreach (KeyValuePair<string, ExchangeTicker> kvp in freshTickers)
                {
                    //Console.WriteLine($"- Bittrex market {kvp.Key}, ticker {kvp.Value}");
                }
            });

BUT APP does not answer!
I have tried to use old versions (from this month) of yout library and it works again!
It seems you broke that!
Can you help me urgent?

**Comment by jjxtra** [comment]
Try latest github code it should work.

Jeff Johnson
CEO / CTO, Digital Ruby, LLC
