### ISSUE TITLE
PlaceOrder function does not convert price variable to string because of regional settings

### ISSUE THREAD

**Issue by gonzotr** [jjxtra/ExchangeSharp#16]
ExchangeBitfinexAPI class PlaceOrder function has a number format bug in price variable (probably all exchange PlaceOrder functions)
My operating systems number format is in Turkish format (dot for digit and comma for decimal symbol). So when i try to use PlaceOrder function, the price variable can not be converted to string correctly. I use ToString(CultureInfo.InvariantCulture.NumberFormat) function at the price variable like you do in amount variable when converting to string to avoid of this problem.

**Comment by jjxtra** [comment]
I've pushed a fix for all order functions

Jeff Johnson
CEO / CTO, Digital Ruby, LLC
