### ISSUE TITLE
LiveCoin - Placing Order: Request is missing required form field 'currencyPair' (issue #123)

### ISSUE THREAD

**Issue by jeffturpin** [jjxtra/ExchangeSharp#160]
I have a [BUG REPORT] 

Details:
Reopen of #123 - I have the same issue, new code did not resolve it.

When trying to place an order on Livecoin, an APIException: 'Request is missing required form field 'currencyPair'.

*** These are NOT my api keys.  They are the keys provided on Livecoin's examples website @ https://www.livecoin.net/api/examples ***.  They do provide the same error message though, whereas their sample code doesn't.

Sample code to reproduce:

            ExchangeAPI ExchangeAPI = new ExchangeLivecoinAPI();
            ExchangeAPI.LoadAPIKeysUnsecure("gJx7Wa7qXkPtmTAaK3ADCtr6m5rCYYMy", "8eLps29wsXszNyEhOl9w8dxsOsM2lTzg");

            decimal amount = .05m;
            bool isBuy = true;
            decimal price = .0157300m;

            ExchangeOrderRequest request = new ExchangeOrderRequest
            {
                Amount = amount,
                IsBuy = isBuy,
                Price = price,
                Symbol = GetTradingPairSymbol(CoinSymbol, CurrencySymbol)
            };
            
            ExchangeOrderResult result = ExchangeAPI.PlaceOrder(request);
            Thread.Sleep(500);
            result = ExchangeAPI.GetOrderDetails(result.OrderId);
            Console.WriteLine(result.Message);

Error Logs (if any):

The more information you can provide, the better.

For new features, please donate or do a pull request. When donating, email the feature request details, coin type and tx id to exchangesharp@digitalruby.com.

Donations will help your bug to get fixed faster.

Requests for new features without a donation or pull request will be ignored due to the high volume of emails and requests. I've done hundreds of hours for free on this project to get a great baseline. I obviously can't continue to spend my time on new features without donations.

**Comment by jjxtra** [comment]
Try latest code now.

**Comment by jeffturpin** [comment]
Holy response time, batman!  I'll give it a go shortly.

**Comment by jeffturpin** [comment]
Perfect.  I'd like to say I was close to tracking that down, but not nearly as quickly as you knocked it out.  Much appreciated.  There's a small BTC transaction headed your way.

**Comment by jeffturpin** [comment]
I spoke too soon, as I have habit to do.  Old error is gone, now it returns an empty API exception.  I'd assumed that was just because of the sample API keys, but it's doing that for my keys also.

So I also spoke while only half-glancing at the commit, and noticed that you were in the same area I was looking at... but I was thinking that it was possibly different.

The Sign header keys are different when generated via your code and the sample code.
When based on the sample API secret on their website (8eLps29wsXszNyEhOl9w8dxsOsM2lTzg)

I noticed that ExchangeSharp headers are:
API-key: gJx7Wa7qXkPtmTAaK3ADCtr6m5rCYYMy
Sign: FEC765B3F9B87CC01BD0640078E986E8EFA7E27867F7C9B95097FF1F72822397

While the example website's header values are:
Api-Key: gJx7Wa7qXkPtmTAaK3ADCtr6m5rCYYMy
Sign: 230E958F1C14ECA81556B91DB08E05F12ADFD41A535ECF045DB45027771FB1F3

I'm thinking that's why it's rejecting the paramaters... but I hadn't figured out how to attempt a fix to test that theory yet.

ExchangeSharp.APIException
  HResult=0x80131500
  Message={
  "success": false,
  "added": false,
  "orderId": null,
  "exception": null
}

**Comment by jjxtra** [comment]
Ok one sec...

**Comment by jeffturpin** [comment]
Oh, I'm dumb.  The sign's are different because I had different order details.  

But now I'm seeing that this is including a nonce parameter very first, and the website states that the parameters have to be in alphabetical order in order for the signing to work.  And their code doesn't even have a nonce value.

**Comment by jjxtra** [comment]
I'm adding param sorting and removing the nonce, will let you know...

**Comment by jeffturpin** [comment]
I tried removing the nonce just now (payload.Clear after generation and before adding the parameters) - back to the first error message.

**Comment by jjxtra** [comment]
Allright, try latest code now...

**Comment by jeffturpin** [comment]
Still an empty exception, with my keys.

ExchangeSharp.APIException
HResult=0x80131500
Message={
"success": false,
"added": false,
"orderId": null,
"exception": null
}

**Comment by jeffturpin** [comment]
... Which is exactly what their code does too.  Maybe this is a problem with my order, or maybe it's a problem with their website.  Hrm.

**Comment by jeffturpin** [comment]
Yep, their stupid code returns the same empty response.  I've got you chasing probably nothing.  I'm sorry!

**Comment by jjxtra** [comment]
The example code gives an exception so it must be something different. Will post back here when it is fixed.

**Comment by jjxtra** [comment]
Please re-open if you see any further issues.

**Comment by jeffturpin** [comment]
Yep, now I see the error codes in the response.  Thank you so much.
