### ISSUE TITLE
HITBTC TimeInForce

### ISSUE THREAD

**Issue by kcabrera99** [jjxtra/ExchangeSharp#161]
I have a [BUG REPORT] 

Details:

HITBTC defaults to IOC (Instant or Cancel) for the TimeInForce value for new orders.  This should be GTC by default, but it should be a parameter that can be passed in with the request.

**Comment by jjxtra** [comment]
Pull latest code. Pass in "ExtraParameters" the "timeInForce" property of whatever value you need, but GTC is now the default for limit orders.

**Comment by kcabrera99** [comment]
Excellent, thanks!
