### ISSUE TITLE
Invalid nonce exception on Kucoin

### ISSUE THREAD

**Issue by mehtadone** [jjxtra/ExchangeSharp#164]
I have a [BUG REPORT] 

Details:

Error Logs (if any):
```
ExchangeSharp.APIException: {
  "code": "UNAUTH",
  "msg": "Invalid nonce",
  "success": false,
  "timestamp": 1527760410368
}
   at ExchangeSharp.ExchangeAPI.CheckError(JToken result)
   at ExchangeSharp.ExchangeKucoinAPI.<OnPlaceOrderAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ExchangeSharp.ExchangeAPI.<PlaceOrderAsync>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

Whilst trying to place an order on Kucoin, I get the following exception. It seems to be related to https://github.com/Satoshinaire/kucoin-api/pull/8 but I'm not sure how to fix it in your library. 

Thanks again for the hard work.

**Comment by jjxtra** [comment]
I've pushed a fix for this, please try it and let me know. It will query for the timestamp offset upon first private API call.

**Comment by jjxtra** [comment]
You'll need to upgrade to .NET core 2.1. The performance benefits are well worth it.

**Comment by mehtadone** [comment]
Appreciate it. I'll be able to test soon

**Comment by jjxtra** [comment]
Please re-open this issue if you still have this problem
