### ISSUE TITLE
Cannot send a content-body with this verb-type.

### ISSUE THREAD

**Issue by Akroni** [jjxtra/ExchangeSharp#165]
I have a [BUG REPORT] or [FEATURE REQUEST]

Details:

When calling the following Method OnGetOpenOrderDetailsAsync, within ExchangeHitbtcAPI

wether or not a symbol is provided, we get the following error: 

"Cannot send a content-body with this verb-type."

**Comment by jjxtra** [comment]
Please pull code and try again. Donations are always appreciated.

**Comment by cutemonster** [comment]
I have the same problem with the latest code, is it fixed?
thanks
