### ISSUE TITLE
Exchange Order Book - GetPriceToBuy/GetPriceToSell

### ISSUE THREAD

**Issue by BobDeCuir** [jjxtra/ExchangeSharp#167]
The Asks and Bids of the ExchangeOrderBook are now Sorted Dictionaries. Cool.

However, the GetPriceToBuy/Sell routines can no longer reference the values by index. You must use ElementAt(i) to grab the value.

**Comment by BobDeCuir** [comment]
For what it's worth, I override these methods in my code because I like to have the depth returned from these calls as well. I use the new dynamic tuple return types instead of out parameters, like so...

  /// <summary>
        /// Get the price necessary to buy at to acquire an equivelant amount of currency from the order book, i.e. amount of 2 BTC could acquire x amount of other currency by buying at a certain BTC price.
        /// You would place a limit buy order for buyAmount of alt coin at buyPrice.
        /// </summary>
        /// <param name="amount">Amount of currency to trade, i.e. you have 0.1 BTC and want to buy an equivelant amount of alt coins</param>
        /// <param name="buyAmount">The amount of new currency that will be acquired</param>
        /// <param name="buyPrice">The price necessary to buy at to acquire buyAmount of currency</param>
        public (decimal Amount, decimal Price, int Depth) GetPriceToBuy(decimal amount)
        {
            ExchangeOrderPrice ask;
            decimal spent;
            decimal buyAmount = 0m;
            decimal buyPrice = 0m;
            int depth = 0;

            for (int i = 0; i < Book.Asks.Count && amount > 0m; i++)
            {
                ask = Book.Asks.ElementAt(i).Value;
                spent = Math.Min(amount, ask.Amount * ask.Price);
                buyAmount += spent / ask.Price;
                buyPrice = ask.Price;
                amount -= spent;
                depth++;
            }
            return (buyAmount, buyPrice, depth);
        }

        /// <summary>
        /// Get the price necessary to sell amount currency. You would place a limit sell order for amount at the returned price to sell all of the amount.
        /// </summary>
        /// <param name="amount">Amount to sell</param>
        /// <returns>The price necessary to sell at to sell amount currency</returns>
        public (decimal Price, int Depth) GetPriceToSell(decimal amount)
        {
            ExchangeOrderPrice bid;
            decimal sellPrice = 0m;
            int depth = 0;

            for (int i = 0; i < Book.Bids.Count && amount > 0m; i++)
            {
                bid = Book.Bids.ElementAt(i).Value;
                sellPrice = bid.Price;
                amount -= bid.Amount;
                depth++;
            }
            return (sellPrice, depth);
        }

**Comment by jjxtra** [comment]
Good catch! Will fix ASAP.

Jeff Johnson
CEO / CTO, Digital Ruby, LLC

**Comment by jjxtra** [comment]
Fixed, new code and nuget sent out.
