### ISSUE TITLE
Binance - GetOrderDetail Price or AveragePrice is not same with Binance.com

### ISSUE THREAD

**Issue by hypersoar2016** [jjxtra/ExchangeSharp#177]
I have a [BUG REPORT] or [FEATURE REQUEST]

Details:
GetOrderDetail gives me the "Price" column on Binance as "AveragePrice" and "Price". I believe it can be fixed, cause API's Price x AmountFilled doesn't give the total BTC. Hope I could explain it.
Thanks

![1](https://user-images.githubusercontent.com/21153880/40927441-638e2e20-6827-11e8-8433-732d789236f7.PNG)

**Comment by jazzonaut** [comment]
There is a fix in one of my recent commits (not approved yet), which does calculate the average price properly. #173 
Look for ParseAveragePriceAndFeesFromFills method.

**Comment by hypersoar2016** [comment]
thank you @jazzonaut you're awesome
