### ISSUE TITLE
Cannot send a content-body with this verb-type.

### ISSUE THREAD

**Issue by cutemonster** [jjxtra/ExchangeSharp#180]
I have a [BUG REPORT] or [FEATURE REQUEST]

Details:
When calling the following Method OnGetOpenOrderDetailsAsync, within ExchangeHitbtcAPI

wether or not a symbol is provided, we get the following error:

"Cannot send a content-body with this verb-type."

Related to this closed bug:
https://github.com/jjxtra/ExchangeSharp/issues/165

With the latest code, still have problem.

**Comment by jjxtra** [comment]
Resolved in 09a1cbb322c0d5aef2654fdbf5057927d6edc02c
