### ISSUE TITLE
Livecoin Public api doesn't work

### ISSUE THREAD

**Issue by SergeevGregory** [jjxtra/ExchangeSharp#185]
I have a bug report. Livecoin Public api doesn't work.
Exception (unfortunatelly only in Russian):
Запрос был прерван: Не удалось создать защищенный канал SSL/TLS.

P.S. I have own library for working with Livecoin Public api. In my implementation all works fine. 

Hope you will fix this issue.

**Comment by jeffturpin** [comment]
Why do you say that?  I use the LiveCoin api extensively using the ExchangeSharp libraries with good success.  

GetSymbolsMetaData() & GetOrderBook() do work for me.

**Comment by jjxtra** [comment]
Windows 8+ only
