### ISSUE TITLE
Possible memory leak in WebSocketWrapper

### ISSUE THREAD

**Issue by jazzonaut** [jjxtra/ExchangeSharp#193]
I think I've found a memory leak in WebSocketWrapper. I believe it's related to messageQueue. 
The memory size slowly rises above 1.5GB, whilst before it was always below ~300MB.

![leak](https://user-images.githubusercontent.com/3920413/41941083-d8cb42c8-7992-11e8-869b-9ef0996b5091.png)

Possibly caused by this commit (just speculating here):
Commit: f1bbdbc707347191e799cc326b7e07701f09a1d9
Switch web socket to raw bytes

**Comment by jjxtra** [comment]
Does the previous commit have the problem?

**Comment by jazzonaut** [comment]
I am not entirely sure when it became a problem, but I'm fairly certain it's a recently introduced issue. I don't remember anything like this a month ago.

**Comment by jazzonaut** [comment]
Ok, the problem is with the WebSocketWrapper not disposing of webSocket object properly (State is still Open) on Dispose(), keeping connection open and accumulating the messages in the messageQueue, while dequeuing them in MessageWorkerThread, because disposed = true.

**Comment by jazzonaut** [comment]
The problem is with webSocket.CloseAsync throwing the following exception:

> System.Net.WebSockets.WebSocketException: 'The remote party closed the WebSocket connection without completing the close handshake.'

This is on ExchangeBinance by the way.

**Comment by jazzonaut** [comment]
Found a fix, pull request: https://github.com/jjxtra/ExchangeSharp/pull/194
