### ISSUE TITLE
Bitfinex order price little bug

### ISSUE THREAD

**Issue by malmaxser** [jjxtra/ExchangeSharp#198]
Hi.

I'm found a little bug in Bitfinex OnPlaceOrder method.
https://github.com/jjxtra/ExchangeSharp/blob/master/ExchangeSharp/API/Exchanges/Bitfinex/ExchangeBitfinexAPI.cs#L403

ClampOrderPrice is async, but await is missing.
Can someone fix that please.

Thanks!

**Comment by Revetter** [comment]
Fixed and made a pull request.
