### ISSUE TITLE
Exchange Yobit  [GetOrderDetails]

### ISSUE THREAD

**Issue by Xnodepro** [jjxtra/ExchangeSharp#208]
I have a [BUG REPORT] or [FEATURE REQUEST]

Details: Exchange Yobit
var resulta =  Api.GetOrderDetails(result.OrderId);

Error Logs (if any):
Cannot access child value on Newtonsoft.Json.Linq.JProperty

**Comment by jjxtra** [comment]
Please post json response here.

**Comment by jjxtra** [comment]
Please re-open if you want to try and resolve this.
