### ISSUE TITLE
Bittrex SignalR websocket does not resubscribe after disconnect

### ISSUE THREAD

**Issue by bichuga** [jjxtra/ExchangeSharp#210]
I was noticing that my Bittrex order book gets way out of date after a while. When debugging I found that if I simulate a disconnect via fiddler or [cports](https://www.nirsoft.net/utils/cports.html#DownloadLinks) I see the socket reconnect but nothing is subscribed anymore. I believe this is the bug. (FWIW, I've also been seeing Binance order book information out of date though I'm less sure of the cause.)

Before reconnect:
![image](https://user-images.githubusercontent.com/9372553/42796236-95ec75c0-893d-11e8-9a09-4f44ef701a4c.png)

After reconnect:
![image](https://user-images.githubusercontent.com/9372553/42796243-a36da282-893d-11e8-9598-59a5347a18d9.png)

I was attempting to fix this bug, but I can't get any of my events to fire on reconnect. I get no "Reconnecting" or "StateChanged" event when it magically reconnects the socket, otherwise I'd be able to reissue the subscribe messages.

![image](https://user-images.githubusercontent.com/9372553/42796283-f971b7a4-893d-11e8-84b0-043672b550de.png)

**Comment by jjxtra** [comment]
I tested this a while back. Simply disable the network adapter wait 5-10 secs and plug it back in. Let me know what that does for you.

**Comment by jjxtra** [comment]
I am able to disconnect and reconnect with Binance, no problem using the console app.

ags: websocket-tickers exchangeName=Binance

**Comment by bichuga** [comment]
What happens in bittrex? I don't think binance uses signalr

**Comment by jjxtra** [comment]
I've checked in a possible fix. Let me know how it works for you.

**Comment by bichuga** [comment]
I'll try this when I get home. However yesterday it wasn't even hitting the
LostConnection code path for me on disconnect. I had a breakpoint there as
well

**Comment by jjxtra** [comment]
I have a fix and it is ugly and required all afternoon to fix. Will check in soon.

**Comment by bichuga** [comment]
I tried this out and pulling the network cable definitely works differently
than killing the TCP connection in Fiddler. Did you use another project as
a guide for creating this signalr implementation? I was looking at the
official signalr docs and they handle things rather differently. When
pulling the network cable, things reconnect and resubscribe as expected.

https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events

I added a property on the order book to track when it was last updated to
try and see where things are getting out of date or if your change solved
it. I'll report back. Thanks for looking into this!

**Comment by jjxtra** [comment]
I didn't use any other guides. I did notice that things did not automatically connect, and nothing got in the right state again unless I tore literally everything down and recreated it from scratch upon a disconnect.

**Comment by jjxtra** [comment]
Checked in some more fixes this morning for short disconnect periods.

**Comment by szmcdull** [comment]
Seems there is still some problem with Bittrex signalr. If the connection is dead but it still seems  connected, no reconnection is performed. Is the KeepAlive property not working?

**Comment by szmcdull** [comment]
I notice the Bittrex signalR connection is dead every 10 minutes. A few days ago I remember it was every 5 minutes.

**Comment by jjxtra** [comment]
I don't have bandwidth to look into it, you are welcome to do so if you have time.

**Comment by szmcdull** [comment]
Sorry. It turns out to be my fault. The story is a little bit long. As you know, ExchangeMarketSymbolToCurrenciesAsync() is now async. But it is really hard to change a bunch of sync code to async. Because whole call paths have to be changed. So I made a cache of symbol meta data and wrote my own translator. Once the cache is available, the translator can find out the symbol and take the base and quote currency from it. It all works fine at the start. But I forget that the cache has a TTL of 10 mins. That is why after 10 mins there would not be any more callbacks. It fails to translate symbols.

**Comment by jjxtra** [comment]
Just a heads up that this and many other methods are cached by default. So writing your own cache layer is not needed.
