### ISSUE TITLE
kucoin OnGetAmountsAvailableToTradeAsync and OnGetAmountsAsync

### ISSUE THREAD

**Issue by username77** [jjxtra/ExchangeSharp#219]
using those functions on kucoin OnGetAmountsAvailableToTradeAsync and OnGetAmountsAsync it show only 12 coins as default and not all coins balances 
for more details here :
https://kucoinapidocs.docs.apiary.io/#reference/0/assets-operation/get-balance-by-page

Attributes
limit
number
page limit，default 12，max 20

page
number
page number，default 1

**Comment by jjxtra** [comment]
You are most welcome to submit a pull request, we love code from anyone and everyone here.
