### ISSUE TITLE
NullRef in SignalrManager

### ISSUE THREAD

**Issue by bichuga** [jjxtra/ExchangeSharp#227]
BUG REPORT:

Error invoking hub proxy SubscribeToExchangeDeltas: System.NullReferenceException: Object reference not set to an instance of an object.
   at ExchangeSharp.SignalrManager.SignalrSocketConnection.<OpenAsync>d__10.MoveNext() in ExchangeSharp\ExchangeSharp\API\Common\SignalrManager.cs:line 80

```
if (!(await manager.hubProxy.Invoke<bool>(functionFullName, param[i])))
{
    throw new APIException("Invoke returned success code of false");
}
```

hubProxy is null on `await manager.hubProxy.Invoke`

**Comment by jjxtra** [comment]
Is this happening from the console app when doing web socket order book?

**Comment by Ofekw** [comment]
Seems to be working from the console app - we think it may be a race condition. Investigating :)

**Comment by jjxtra** [comment]
Let me know if you find anything. Hopefully it's an easy fix.

**Comment by jjxtra** [comment]
I've added additional code to check nulls and to try and avoid this. Let me know if it still has problems, jus re-open the issue.
