### ISSUE TITLE
[BUG] - New naming enforcement breaking hundreds of our tests

### ISSUE THREAD

**Issue by Ofekw** [jjxtra/ExchangeSharp#228]
New changes are breaking our tests. There are several new enforcement for naming conventions which are fine (although I do believe these should simply be enforced through code reviews rather than via code), however these enforcements are breaking our personal tests. 

Specifically in BaseAPI.cs
```
        public ExchangeAPI()
        {
            if (!ExchangeName.HasName(Name))
            {
                throw new ArgumentException("Exchange class name must follow this format: Exchange[A-Za-z0-9]API");
            }
        }
```

and ExchangeAPI.cs
```
        public ExchangeAPI()
        {
            if (!ExchangeName.HasName(Name))
            {
                throw new ArgumentException("Exchange class name must follow this format: Exchange[A-Za-z0-9]API");
            }
        }
```
An example of some of use cases - We have several tests that mock out the exchangeAPI using NSubstitute which appends "Proxy" to the class name - this now breaks. 

Repro - `Substite.For<ExchangeApi>()`

I suggest these argumentExceptions (which are more like class name exceptions?) be changed to warnings or removed all together.

Looking forward to hearing your thoughts. 

Cheers.

**Comment by jjxtra** [comment]
I’ll make the name be the class name if the pattern doesn’t match. Also in such case the class will not get added to the exchange apis dictionary.

**Comment by jjxtra** [comment]
Commented out for now. Will fix it up better when I get home.

**Comment by jjxtra** [comment]
I've removed the exception case and added an ApiNameAttribute for cases where you want a proper api name but want to name your class something else.

**Comment by Ofekw** [comment]
Thanks - very much appreciated!
