### ISSUE TITLE
ExchangeAPIExtensions.GetOrderBookWebSocket does not process messages synchronously anymore

### ISSUE THREAD

**Issue by bichuga** [jjxtra/ExchangeSharp#230]
When using GetOrderBookWebSocket to subscribe to order books, the expectation is that the first time a book update is seen, it fetches the entire order book and then from there it will process deltas. This is what the behavior used to be. Something regressed recently (last 0-3 weeks?).

Now it _appears_ to be attempting to subscribe to all books at the same time. This results in many fetches for the same full order book and eventually I get throttled by Binance due to too many heavy requests.

For example, this should never be able to happen:
![image](https://user-images.githubusercontent.com/9372553/43682018-ca108f44-981a-11e8-9cd0-8e82909328c2.png)

**Repro**
`                
this.Client = new ExchangeBinanceAPI();
IEnumerable<string> syms = await this.Client.GetSymbolsAsync();
this.Client.GetOrderBookWebSocket(updates => { this.AllOrderBooks[updates.Symbol] = updates; }, 1000, syms.ToArray());`

In my screenshot, multiple updates for the same book are getting inside the if (!foundFullBook) resulting is reaching line 90 to request the same full order book.

![image](https://user-images.githubusercontent.com/9372553/43682046-e34a2898-981b-11e8-839c-c33d653cc4f7.png)

**Comment by jjxtra** [comment]
I see it to. The "await api.GetOrderBookAsync" is the culpript, as this causes the callback to yield, allowing the web socket to then process more messages. We need to queue up or throw out deltas until that full book request finishes. I wish these exchanges would just return a full book for the first request... sigh.

**Comment by bichuga** [comment]
If there was a way to lock on the fact that we were processing a certain ticker symbol, but only if that symbol was not found in the dictionary, that might work. I'm not sure yet how to turn that from a concept into code.

Something like this pattern, but new BittrexWebSocketManager would be our call for the order book.
```
        private BittrexWebSocketManager SocketManager
        {
            get
            {
                if (webSocket == null)
                {
                    lock (this)
                    {
                        if (webSocket == null)
                        {
                            webSocket = new BittrexWebSocketManager();
                        }
                    }
                }
                return webSocket;
            }
        }
```

What about a dictionary of locks, one for each ticker symbol?

**Comment by jjxtra** [comment]
I fixed this extension method, similar to what you suggested but let me know if you have suggestions on improvement for the latest commit.
