### ISSUE TITLE
bitMEX bug

### ISSUE THREAD

**Issue by wukan1986** [jjxtra/ExchangeSharp#231]
in GetJsonForPayload the PayloadKeyArray is not exist

```
object singleton = null;
payload.TryGetValue(PayloadKeyArray, out singleton);
```

the default ratelimit is 5 request
so if I send 10 orders, the last 5 order will be rejected. the api-expires is expired.

**Comment by jjxtra** [comment]
Are you calling PlaceOrders or PlaceOrder?

**Comment by jjxtra** [comment]
Just FYI I increased the BitMex order window to 60 seconds and the rate to 1 call/2 seconds

**Comment by wukan1986** [comment]
I call PlaceOrder

**Comment by jjxtra** [comment]
Call PlaceOrders (plural). Pass array of orders, get array of order results back.

**Comment by jjxtra** [comment]
Please re-open the issue if "PlaceOrders" is not working.
