### ISSUE TITLE
Coinbase SymbolIsReversed

### ISSUE THREAD

**Issue by BobDeCuir** [jjxtra/ExchangeSharp#237]
Could you please verify the Coinbase SymbolIsReversed property?

It would appear it should be True based on the standard format of CurFrom-CurTo (i.e. BTC-ETH). It defaults to False, though I'm not sure the standard order. I have to set it in my code to True (even though it's a protected field), so I either have to Flag this as reversed outside the API, or change my order internally (yuck).

Also, line 48 in ExchangeCoinbaseAPI should be:
string symbol = result[**"product_id"**].ToStringInvariant();

It is populating the Order with the OrderID instead of the Symbol (market)

**Comment by jjxtra** [comment]
Looks good, checked it in.

**Comment by BobDeCuir** [comment]
Thanks! You're the best!
