### ISSUE TITLE
Some General Questions

### ISSUE THREAD

**Issue by hasintel85** [jjxtra/ExchangeSharp#248]
Hi,

I briefly reviewed ExchangeSharp and found it one of the best APIs along with CCXT and the top one for me in C#. I ve couple of questions, if you don't mind.

1) Is there any road map planned to improve this project further? 

2) Are you going to support DEX like IDEX? If No, do you offer paid services to add it? If Yes, can you give an estimate (cost and duration)?

3) Is there any wrapper in the API, where one call methods from all supported exchanges by giving the Exchange Name along with other info like symbol and API Keys, or to integrate the API in our project, we will have to add cases for all different exchanges ourselves? My apologies in advance for asking a very basic question and not looking into the code directly.

Thanks

**Comment by jjxtra** [comment]
1- Architecture wise it’s good. No additional work needed. Additional
exchanges may be added in the future but it’s all volunteer work so no
roadmap.

2- I do contract work. But I ask for all payment up front. 150/usd hour. I
am planning on dex support. That is the future of trading. No plans to do
this short term in my volunteer work however.

3- ExchangeAPI.cs has a method to get all exchanges or to get an exchange
by name.

- Jeff
