### ISSUE TITLE
Bitfinex Nonce is too small

### ISSUE THREAD

**Issue by philipp-troxler** [jjxtra/ExchangeSharp#256]
I have a [BUG REPORT]

Details:

With the actual implementation of the BitfinexAPI a call to GetOrderDetailsAsync(...) returns allways 'nonce is too small'. Only with a NonceStyle of TicksString (1) works the call.

Best regards
Philipp Troxler

**Comment by jjxtra** [comment]
Not seeing the problem. Try new API key.
