### ISSUE TITLE
Streaming when using SignalrManager does not fire Connected event consistently

### ISSUE THREAD

**Issue by vslee** [jjxtra/ExchangeSharp#263]
I have a bug report

Details: SignalrManager does not fire Connected event consistently. Can repro with the code below. The problem appears to be in SignalrManager.cs line 91,  where it awaits AddListener(), which in turn awaits EnsureConnected(). This means that line 141 where the socket is added to sockets doesn't happen until after the connection is already made. Thus, line 522 (await socket.InvokeConnected();) doesn't occur. 

```c#
	       static async Task Main(string[] args)
		{
			var exchangeAPI = new ExchangeBittrexAPI();
			using (var socket = exchangeAPI.GetTradesWebSocket(kvp =>
				{
					Console.WriteLine($"{kvp.Key}, {kvp.Value}");
				}, new string[] { "USDT-BTC", "USD-BTC", "BTC-LTC", "BTC-ETH" }))
			{
				socket.Connected += async s =>
					Console.WriteLine("connected");
				socket.Disconnected += async s => Console.WriteLine("disconnected");
				Console.WriteLine("Press ENTER to shutdown.");
				Console.ReadLine();
			}
                }
```

**Comment by jjxtra** [comment]
Resolved with pull request #266 , thanks so much for doing that!

**Comment by vslee** [comment]
Oops, sorry I forgot to mention that the pull request and this issue are unrelated.
For this issue, I am seeing if you could fix because the fix would involve changing the structure of SignalrManager.

**Comment by jjxtra** [comment]
Does connect not get called initially or is it not called if the socket disconnects and reconnects, or is it not called regularly on intervals?

**Comment by vslee** [comment]
It does not get called initially after the first connection. 
Eventually, after the socked disconnects and reconnects, then it appears to be called, although not sure about that. 
It does get called on regular intervals due to ConnectInterval.

**Comment by jjxtra** [comment]
I checked in code to do this, let me know if it doesn't work and re-open the issue.

**Comment by vslee** [comment]
I tried out the new code. It now fires the initial Connected event. However, it seems to get stuck and no longer streams the resulting trades after that.

**Comment by jjxtra** [comment]
That problem looks like a separate issue. I don't get any stream even with reverting my last checkin.

**Comment by jjxtra** [comment]
No I take that back, my fault, checked in some more code, try it again.

**Comment by vslee** [comment]
Could you go a git push? I can't see the new code yet.

**Comment by jjxtra** [comment]
Ok it's pushed, sorry about that.

**Comment by vslee** [comment]
The streaming portion is working again. However, there is a delay prior to the Connected event being fired. This means a bunch of trade events are streamed prior to the Connected event being fired. 

![image](https://user-images.githubusercontent.com/366757/50379302-78047900-05fb-11e9-98cb-2844468c1a7a.png)

**Comment by jjxtra** [comment]
I'm open to ideas on how to get around that. Can't fire it immediately
because the event handler hasn't been set yet, so had to add enough delay
to guarantee it fires after the property has been set.

-- Jeff

**Comment by vslee** [comment]
The way you have it in ClientWebSocket.cs seems to work pretty well. There, you create the websocket, which is a nonblocking call. Then you start the MessageTask and ReadTask running and return back to the caller to set the Connected and Disconnected event handlers. By the time the MessageTask and ReadTask do anything, the event handlers are already set. 

```c#       /// <summary>
        /// Start the web socket listening and processing
        /// </summary>
        public void Start()
        {
            CreateWebSocket();

            // kick off message parser and message listener
            Task.Run(MessageTask);
            Task.Run(ReadTask);
        }
```

**Comment by vslee** [comment]
Or could incorporate the implementation used here: https://github.com/JKorf/Bittrex.Net

**Comment by vslee** [comment]
nvm, his implementation also doesn't return until after the connection is made and the subscribed.

**Comment by jjxtra** [comment]
I could probably add something to the Connected event setter that fires it once upon being set if the connection has been established. Would that work?

**Comment by vslee** [comment]
Actually, don't worry about it. I'll just change my code a bit to compensate. If I think of a way to fix this in the future, I'll send a PR.

**Comment by jjxtra** [comment]
Ok sounds good!
