### ISSUE TITLE
SignalRManager AddListener

### ISSUE THREAD

**Issue by razorbohan** [jjxtra/ExchangeSharp#270]
Trying looking for a **functionName** while listeners' key is **functionFullName**

Is:
https://github.com/jjxtra/ExchangeSharp/blob/a320b360ba0c55150a3af441bf0a17dff6ef16e0/ExchangeSharp/Utility/SignalrManager.cs#L418-L421

Should be:
```C#
if (!listeners.TryGetValue(functionFullName, out HubListener listener))
```

Don't you think?

**Comment by jjxtra** [comment]
Thanks for reporting
