### ISSUE TITLE
[FEATURE REQUEST] Setup CI to validate builds / pull requests

### ISSUE THREAD

**Issue by superhappychris** [jjxtra/ExchangeSharp#274]
As more people contribute to the project, I think it makes sense to add some safeguards against simple mistakes like the one that just occurred with pull request #269 .. 

Microsoft recently made CI builds for open source projects free on the Azure Dev Ops platform. [Here's an article on how to set it up](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-public?view=vsts&tabs=github)

**Comment by jjxtra** [comment]
This is complete and on azure build pipelines.

https://dev.azure.com/DigitalRuby/DigitalRuby/_build?definitionId=5
