### ISSUE TITLE
ExchangeGlobalCurrencyReplacements erasing after filling

### ISSUE THREAD

**Issue by razorbohan** [jjxtra/ExchangeSharp#281]
I think it's a kind of [BUG REPORT] or [Misunderstanding]

What is the point of filling **ExchangeGlobalCurrencyReplacements** in static constractor like:

https://github.com/jjxtra/ExchangeSharp/blob/b7680f7e040a1dca172c778e32fb5c09966a7c57/ExchangeSharp/API/Exchanges/Binance/ExchangeBinanceAPI.cs#L39-L45

if we erase it right after it here:

https://github.com/jjxtra/ExchangeSharp/blob/b7680f7e040a1dca172c778e32fb5c09966a7c57/ExchangeSharp/API/Exchanges/_Base/ExchangeAPI.cs#L175-L189

May be it'll be better to put `ExchangeGlobalCurrencyReplacements[type] = new KeyValuePair<string, string>[0];` before ExchangeAPI's instantiating?

**Comment by jjxtra** [comment]
Fixed in latest code
