### ISSUE TITLE
Retrieve my withdrawls, trades and deposits

### ISSUE THREAD

**Issue by exchangedude** [jjxtra/ExchangeSharp#292]
Hello, I am looking to see if this project allows the following...

Retrieval of all of my Trades, and
Retrieval of all of my Withdrawls

Thanks

**Comment by pomeara** [comment]
Is this available?

**Comment by bichuga** [comment]
Yes this is available for most exchanges.

**Comment by exchangedude** [comment]
Can you list the calls please as I cannot locate them.
