### ISSUE TITLE
Get open orders

### ISSUE THREAD

**Issue by zachtdavis** [jjxtra/ExchangeSharp#3]
Am I crazy or is there no "get open orders" on a pair?

example: get open orders for BTC-USD on gdax

I see that I can place and cancel orders, but you need the order ID, which I cannot get unless I placed the order and saved the ID (which is not always the case). I see I can get the order books, but thats not helpful in this scenario.

Thanks for the awesome solution btw! This is really well done!

**Comment by jjxtra** [comment]
You're right, I haven't implemented that end point yet.

**Comment by zachtdavis** [comment]
Ok no worries, I was looking this over and its incredibly well done and feature rich and I thought I was just missing something haha. Thanks for the fast response!

**Comment by jjxtra** [comment]
Looks like I haven't done any of the gdax private API yet.

**Comment by zachtdavis** [comment]
I would love the get open orders functionality on bittrex/gdax, if possible!

**Comment by jjxtra** [comment]
I added get open orders for the bittrex API. No plans yet for gdax but may add if there is enough interest.

**Comment by zachtdavis** [comment]
Youre the best! thank you!
