### ISSUE TITLE
Cryptopia api changed 

### ISSUE THREAD

**Issue by jjziets** [jjxtra/ExchangeSharp#301]
I notice my bot stop working. I'm using nuget so I'm not sure how to get the changed in the the repository. 

But in short get open order throws an exception of value larger or smaller than int32 allow. 

I will debug later but if someone has run in to this place let me know.

**Comment by jjziets** [comment]
OK, this is beyond my skill. The NuGet despotry of ExhangeSharp 0.5.8 worked until two days ago. Not it gets some error. The master on github does not work. I downloaded the master and added it as a solution but get ticker goes into an infinite loop and I can't follow it.

**Comment by jjziets** [comment]
looks like im stuck in        

public static T Sync<T>(this Task<T> task)
        {
            return task.ConfigureAwait(false).GetAwaiter().GetResult();
        }

and not sure for what. no matter what function i call with it it just get stuck in the thread

**Comment by jjziets** [comment]
the pain of waiting and hoping that someone will fix Cryptopia

**Comment by kcabrera99** [comment]
I'm using NuGet as well.  
It looks like the Cryptopia order IDs are now larger than what 32 bit integer can handle.  It needs to be updated to a 64 bit integer.

**Comment by jjxtra** [comment]
Resolved in latest commit

**Comment by jjziets** [comment]
@kcabrera99  can you get cryptopia to work now?

**Comment by jjziets** [comment]
then I am doing something wrong that might be simple 

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using ExchangeSharp;
using System.Threading.Tasks;

namespace WindowsFormsApp3
{
    public partial class Form1 : Form
    {
        private ExchangeCryptopiaAPI cryptopiaAPI = new ExchangeCryptopiaAPI();
        private Timer TimerRefresh;

        public Form1()
        {
            InitializeComponent();
            this.Text = Application.ProductName + " [v" + Application.ProductVersion + "]";
            cryptopiaAPI.LoadAPIKeysUnsecure("##################", "###############");
      
            TimerRefresh = new Timer();
            TimerRefresh.Interval = 300000;
            TimerRefresh.Tick += new EventHandler(button1_Click);
            TimerRefresh.Start();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            ExchangeTicker ticker;
            toolStripProgressBar1.Value = toolStripProgressBar1.Minimum;;
            toolStripProgressBar1.Step = 1;
            toolStripProgressBar1.Maximum = 7;

            toolStripProgressBar1.PerformStep(); //1

            try
            {
                toolStripStatusLabel1.Text = "Geting Ticker for BIS_BTC";
                toolStrip1.Update();
                ticker = cryptopiaAPI.GetTickerAsync("BIS/BTC").Sync();
                toolStripProgressBar1.PerformStep(); // 2
                toolStrip1.Update();

            }
            catch
            {
                listView1.Items.Add("Error getting GetTickerAsync");
                toolStripProgressBar1.Value = toolStripProgressBar1.Maximum;
                toolStrip1.Update();

                return;
            }


            decimal MyPrice = 0;



            try
            {
                toolStripStatusLabel1.Text = "Getting order detials";
                IEnumerable<ExchangeOrderResult> MyOrders = cryptopiaAPI.GetOpenOrderDetailsAsync().Sync();
                toolStripProgressBar1.PerformStep(); // 3
                toolStrip1.Update();

                foreach (ExchangeOrderResult O in MyOrders)
                {
                    if (O.MarketSymbol.Contains("BIS/BTC"))
                        if (O.Price != ticker.Ask) cryptopiaAPI.CancelOrderAsync(O.OrderId).Sync();
                        else MyPrice = O.Price;
                }
            } catch (Exception ex)
            {
                listView1.Items.Add("Error getting GetOpenOrderDetailsAsync " + ex.Message);
                toolStripProgressBar1.Value = toolStripProgressBar1.Maximum;
                toolStrip1.Update();
                return;

            }


            decimal BIS = 0;
            try
            {
                toolStripStatusLabel1.Text = "Getting Amounts Available To Trade";
                toolStrip1.Update();
                Dictionary<string, decimal> balances = cryptopiaAPI.GetAmountsAvailableToTradeAsync().Sync();

                toolStripProgressBar1.PerformStep(); // 4
                toolStrip1.Update();
                foreach (KeyValuePair<string, decimal> entry in balances)
                {

                    if (entry.Key.Contains("BIS") == true) BIS = entry.Value;
                }
            } catch (Exception ex)
            {
                listView1.Items.Add("Error getting GetAmountsAvailableToTradeAsync " +ex.Message);
                toolStripProgressBar1.Value = toolStripProgressBar1.Maximum;
                toolStrip1.Update();
                return;

            }


            decimal min = BIS * ticker.Ask;

            if (min > (decimal)0.00050000 )
            {
                try
                {
                    if (MyPrice > ticker.Ask) MyPrice = ticker.Ask - (decimal)0.00000001;
                    else
                    {
                        if ((ticker.Ask - ticker.Bid)== (decimal)0.0000001) MyPrice = ticker.Bid; else    MyPrice = ticker.Ask;
                    }

                    
                    toolStripStatusLabel1.Text = "Placing Order for " + BIS.ToString() + " BIS @ " + MyPrice.ToString();

                    toolStripProgressBar1.PerformStep(); // 5
                    toolStrip1.Update();

                    ExchangeOrderResult result = cryptopiaAPI.PlaceOrderAsync(new ExchangeOrderRequest
                    {
                        Amount = BIS,
                        IsBuy = false,
                        Price = MyPrice,
                        OrderType = 0,
                        MarketSymbol = "BIS_BTC"

                    }).Sync();
                    listView1.Items.Add(result.Result.ToString() + " " + System.DateTime.UtcNow.ToShortDateString() + " " + System.DateTime.UtcNow.ToShortTimeString() + " BSI " + BIS.ToString() + " " + ticker.Ask.ToString());
                }
                catch (Exception ex)
                {
                    listView1.Items.Add("Error getting PlaceOrderAsync "+ex.Message);
                    toolStripProgressBar1.Value = toolStripProgressBar1.Maximum;
                    toolStrip1.Update();
                    return;
                }
                 

             
            }

            toolStripProgressBar1.PerformStep(); // 6
            toolStripStatusLabel1.Text = "Getting All Balances";
            toolStrip1.Update();
            button2_Click(null, null);
            toolStripProgressBar1.Value = toolStripProgressBar1.Maximum;
            toolStrip1.Update();

        }

        private void button2_Click(object sender, EventArgs e)
        {
            try
            {
                Dictionary<string, decimal> balances = cryptopiaAPI.GetAmountsAsync().Sync();
                ExchangeTicker ticker = cryptopiaAPI.GetTickerAsync("BIS_BTC").Sync();


                ExchangeOrderBook OB = cryptopiaAPI.GetOrderBookAsync("BIS_BTC", 1).Sync();

                string stats = "BIS Bid: " + ticker.Bid.ToString() + " Ask: " + ticker.Ask.ToString() + " Last trade: " + ticker.Last.ToString();


                foreach (KeyValuePair<string, decimal> entry in balances)
                {

                    stats += " " + entry.Key + " " + entry.Value.ToString();

                }
               toolStripStatusLabel1.Text = stats;

            }
            catch
            {
                toolStripStatusLabel1.Text = "Error updating status bar";
             }
            finally
            {
                toolStripStatusLabel1.Text = "finally:Error updating status bar";
            }
        }

        private void statusStrip1_ItemClicked(object sender, ToolStripItemClickedEventArgs e)
        {

        }

        private void toolStripStatusLabel1_Click(object sender, EventArgs e)
        {

        }

        private void listView1_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void toolStripProgressBar1_Click(object sender, EventArgs e)
        {

        }

        private void toolStrip1_ItemClicked(object sender, ToolStripItemClickedEventArgs e)
        {

        }
    }
}

**Comment by kcabrera99** [comment]
If I used the exchangesharp project as a separate solution and then just added it as a reference in my solution, it would not work because it would detect it as the same version and not update the libraries.  So I had to add the exchangesharp project as part of my solution.

**Comment by kcabrera99** [comment]
If you look at the exchangesharp source code, the orderID is now a string so it should be able to handle any value.

**Comment by jjziets** [comment]
@kcabrera99  So you downloaded the master and copied it as part of your project solutions? 

Not like this?

![image](https://user-images.githubusercontent.com/19214485/49380373-35493280-f71a-11e8-92e8-496bac907ca8.png)

If I do the copy thing I get loads of errors. The nuget was easy.

**Comment by kcabrera99** [comment]
Yes, I downloaded the code, added the project to my solution, then added a reference to the project.  Whenever I compiled it and tried to reference it that way, it would still show as version 0.5.8 so visual studio would just ignore the new version

**Comment by jjziets** [comment]
I see that. The DLL is version 0.5.8 but that is just due to the AssemblyVersion stated in AssemblyInfo.cs. if i change that to 0.5.9 the DLL is also 0.5.9

I don't get errors or warnings. Just does not except the t task. But I see this is happening with my other exchanges code if I change to source from the nuget.

**Comment by jjziets** [comment]
Getting the same problem with my binance bot. use to use the nuget but if I add at as a repository/ reference it does not exist the t task.  Clearly, I am doing something wrong.  @kcabrera99 any chance you can provide a step by step?

**Comment by jjziets** [comment]
@kcabrera99 my problem is i can't get any of the exchanges to work with when i sue the GitHub repository as re-reference. 
![image](https://user-images.githubusercontent.com/19214485/49589583-6f147600-f972-11e8-8143-c20f50a5c632.png)
![image](https://user-images.githubusercontent.com/19214485/49589616-82274600-f972-11e8-9af3-65b847e9aa6a.png)

My task het stuck in 

public static T Sync<T>(this Task<T> task)
        {
            return task.ConfigureAwait(false).GetAwaiter().GetResult();
        }

![image](https://user-images.githubusercontent.com/19214485/49589708-bd297980-f972-11e8-9501-78dec1d05799.png)

**Comment by jjziets** [comment]
that is why I ask for a step by step on how to link or add /ExchangeSharp to my project. Clearly this method does not work.

**Comment by kcabrera99** [comment]
I downloaded the solution and then added just the exchangesharp project as a project in my solution.  I didn't add any of the other projects, like the console or the tests.  Then I added a reference to the exchangesharp project in the project that contains my code.
