### ISSUE TITLE
Testnet support?

### ISSUE THREAD

**Issue by nh43de** [jjxtra/ExchangeSharp#307]
What do you all think about adding support for testnet API support?

e.g. 

            var d = new ExchangeHitbtcAPI();
            d.UseTestNet = true;

**Comment by vslee** [comment]
I'm open to the idea if it is implemented in an exchange neutral fashion. For example, Coinbase Pro has a sandbox endpoint so the API for connecting to that should be the same as for the HitBTC testnet.

**Comment by nh43de** [comment]
> I'm open to the idea if it is implemented in an exchange neutral fashion. For example, Coinbase Pro has a sandbox endpoint so the API for connecting to that should be the same as for the HitBTC testnet.

Could you elaborate a little more on that one?

**Comment by vslee** [comment]
For example, the user shouldn't need to remember whether for a particular exchange, it is called testnet or sandbox or whatever. Not a huge nitpick. Just that the d.UseTestNet should be in the IExchangeAPI and be consistent across all exchanges.

**Comment by jjxtra** [comment]
You can set the base url to the test end point
