### ISSUE TITLE
A few questions about speed.

### ISSUE THREAD

**Issue by ivanKo123** [jjxtra/ExchangeSharp#308]
Hello. 
I carried out various tests of your library and faced a problem of big delays when drawing the warrant in a glass of the Binance exchange. I will explain.
The matter is that function of inquiry of glass data (GetOrderBookAsync), at inquiry, obtains data quickly (less than 1 sec. Speed of updating is actually higher. We tested 20 times in sec. And it worked.) 
Function of receiving trades (GetCompletedOrderDetailsAsync), also, obtains data with high speed ( 20 times in sec.)
And here about placement of the order in a glass, I have a problem. The PlaceOrderAsync function is responsible for it. And for Binance the speed is 2-3 sec. I carried out a set of tests. And this average time. It is very bad, in our case. 
Could you, give advice or the recommendation how it is possible to increase the speed of Function PlaceOrderAsync? Perhaps to change something in the code of your library?
P.S. tests of PlaceOrderAsync for HitBtc showed an average delay no more than 1 sec.
Thank you.

**Comment by bichuga** [comment]
That slowdown is probably server side but if you want to grab a perf trace
using visual studio to verify where exactly the slowdown is that's what I'd
recommend.
