### ISSUE TITLE
Bitfinex api is now at version 2.0, CANDLES endpoint can give us OHLC data

### ISSUE THREAD

**Issue by islandTraderFX** [jjxtra/ExchangeSharp#31]
AMAZING job!  Thanks for a project in c#.  Not many of us out there as everyone seems to love python and java variants.

islandTraderFX

**Comment by jjxtra** [comment]
It already has implemented candles API on v2

**Comment by islandTraderFX** [comment]
Just a stupid question, but the Bitfinex getcandles only returns 120 candles, no matter what start and stop time I place. The v1 api doesn't even do candles, but v2 has the candles endpoint, and an unpublished limit of 1000 (from experimenting).

Bittrex getcandles returns about 1420 with same start and end times.

            int i = 0;
            var dd = apiBitfinex.GetCandles("ETHBTC", 3600, new DateTime(2017, 2, 8), new DateTime(2018, 2, 11));
            foreach(var c in ddf)
            {
                Console.WriteLine(i.ToString() + "  " + c.Timestamp.ToShortDateString() + "  " + c.Timestamp.ToShortTimeString() + "  " + c.ClosePrice.ToString());
                i++;
                Application.DoEvents();
            }
