### ISSUE TITLE
[Feature Request] [Bitfinex] [WS] Is anyone coding the Order Updates?

### ISSUE THREAD

**Issue by reathh** [jjxtra/ExchangeSharp#315]
I'm in need of the [https://docs.bitfinex.com/v1/reference#ws-auth-order-updates](Order Updates) functionality. If I understand right, this channel receives data when an order is updated.

 Is anyone coding it? I'm willing to make a fork and code it, but I was wondering what method from the interface should this be? Is it `GetOrderDetailsWebSocket`?

This channel provides information on 3 occasions.
1. "on" New Order
2. "ou" Update Order
3. "oc" Canceled Order.

**Comment by vslee** [comment]
Likely no one else is working on that currently. 

To implement it, you would override the OnGetOrderDetailsWebSocket() method in ExchangeBitfinexAPI.cs.

**Comment by jjxtra** [comment]
Feel free to submit pr if you implement this
