### ISSUE TITLE
[Feature Request] [Bitfinex] Order Fees

### ISSUE THREAD

**Issue by reathh** [jjxtra/ExchangeSharp#316]
I see that the concept for fees is laid in the system. Would love if Bitfinex Order Details came with the fees

**Comment by vslee** [comment]
Thanks for filing this feature request. If you send a pull request, we'll be happy to merge it. If you don't know how, you can also post the updated code here.

**Comment by jjxtra** [comment]
Closing old issues, someone can submit pr if this is still an issue
