### ISSUE TITLE
Binance API Updated

### ISSUE THREAD

**Issue by kcabrera99** [jjxtra/ExchangeSharp#319]
Binance updated their API and they now use "PRICE_PERCENT" instead of "PRICE_FILTER" for the filtertype in their requests.  I updated my local code to just replace that value and my code is working fine.  Not sure if that is the only change that is needed or if there are other dependencies that need updating as well.

**Comment by jjxtra** [comment]
Feel free to submit pr and I will merge it in so you get credit
