### ISSUE TITLE
Bitfinex GetCandles only returns 120 items, but the api v2 will return 1000

### ISSUE THREAD

**Issue by islandTraderFX** [jjxtra/ExchangeSharp#32]
Just a stupid question, but the Bitfinex getcandles only returns 120 candles, no matter what start and stop time I place. The v1 api doesn't even do candles, but v2 has the candles endpoint, and an unpublished limit of 1000 (from experimenting).

Bittrex getcandles returns about 1420 with same start and end times.

Also, it would be great to have a limit param (overload)  instead of times to make it easy to get the latest x candles.

        int i = 0;
        var dd = apiBitfinex.GetCandles("ETHBTC", 3600, new DateTime(2017, 2, 8), new DateTime(2018, 2, 11));
        foreach(var c in dd)
        {
            Console.WriteLine(i.ToString() + "  " + c.Timestamp.ToShortDateString() + "  " + c.Timestamp.ToShortTimeString() + "  " + c.ClosePrice.ToString());
            i++;
            Application.DoEvents();
        }
OUTPUT

.
.
.
116 2/12/2017 8:00 PM 0.01135
117 2/12/2017 9:00 PM 0.011344
118 2/12/2017 10:00 PM 0.01135
119 2/12/2017 11:00 PM 0.01138

**Comment by islandTraderFX** [comment]
My workaround for now...

var dd = apiBitfinex.GetCandles("BTCUSD", 60, DateTime.Now.AddHours(5).AddMinutes(-120), DateTime.Now.AddHours(5));

**Comment by jjxtra** [comment]
Added limit param to API, not all exchanges support but should work for Bitfinex and Binance. You can leave start and end date null.

**Comment by islandTraderFX** [comment]
Thanks.  Strong work.
