### ISSUE TITLE
Can you teach me how to load API keys & Secret for Yobit exchange?

### ISSUE THREAD

**Issue by codeinflash** [jjxtra/ExchangeSharp#320]
I have my keys and secret in my local app.config file.
how can I load keys and secret?

There is no method to load API secret.
ExchangeYobitAPI exchangeYobitAPI = new ExchangeYobitAPI();
exchangeYobitAPI.LoadAPIKeys(APIKeys.yobit_API_KEY);

Thank you.

**Comment by jjziets** [comment]
have you tried 

exchangeYobitAPI.LoadAPIKeysUnsecure("KEY","sKEY");
