### ISSUE TITLE
Help. Can't get ExchangeSharp to work

### ISSUE THREAD

**Issue by jjziets** [jjxtra/ExchangeSharp#321]
I have 2 bots that worked when I was using the NuGet 0.5.8. but the exchanges changed and it stopped working.

So I uninstalled NuGet packet and added the  ExchangeSharp project to my solutions. 
![image](https://user-images.githubusercontent.com/19214485/49608336-0bee0800-f9a1-11e8-8ccd-88640f196320.png)

I then added a reverence to the project.
![image](https://user-images.githubusercontent.com/19214485/49608361-20ca9b80-f9a1-11e8-9a3d-696e52c7766f.png)

I had to change my code as some of the names changes. MarketSymbole for example.  

But now when I do a call my program just hangs in CryptoUtility.cs
        /// <summary>
        /// Make a task execute synchronously
        /// </summary>
        /// <param name="task">Task</param>
        /// <returns>Result</returns>
        public static T Sync<T>(this Task<T> task)
        {
            return task.ConfigureAwait(false).GetAwaiter().GetResult();
        }

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ExchangeSharp;

namespace CryptoPiaBot2
{
    public partial class Form1 : Form
    {

        private ExchangeCryptopiaAPI cryptopiaAPI = new ExchangeCryptopiaAPI();
        private Timer TimerRefresh;

        public Form1()
        {
            InitializeComponent();
            this.Text = Application.ProductName + " [v" + Application.ProductVersion + "]";
            cryptopiaAPI.LoadAPIKeysUnsecure("KEY", "KEY2"); // you need to add yours for 

            TimerRefresh = new Timer();
            TimerRefresh.Interval = 300000;
            TimerRefresh.Tick += new EventHandler(button1_Click);
            TimerRefresh.Start();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            ExchangeTicker ticker;

        }

        private void button2_Click(object sender, EventArgs e)
        {
            try
            {
                Dictionary<string, decimal> balances = cryptopiaAPI.GetAmountsAsync().Sync();
                ExchangeTicker ticker = cryptopiaAPI.GetTickerAsync("BIS_BTC").Sync();

                ExchangeOrderBook OB = cryptopiaAPI.GetOrderBookAsync("BIS_BTC", 1).Sync();

                string stats = "BIS Bid: " + ticker.Bid.ToString() + " Ask: " + ticker.Ask.ToString() + " Last trade: " + ticker.Last.ToString();

                foreach (KeyValuePair<string, decimal> entry in balances)
                {

                    stats += " " + entry.Key + " " + entry.Value.ToString();

                }
                toolStripStatusLabel1.Text = stats;

            }
            catch
            {
                toolStripStatusLabel1.Text = "Error updating status bar";
            }
            finally
            {
                toolStripStatusLabel1.Text = "finally:Error updating status bar";
            }
        }
    }
}
![image](https://user-images.githubusercontent.com/19214485/49608664-e6153300-f9a1-11e8-92a3-0b3f2e6b39ce.png)

What am I doing wrong? Im on windows 7 64bit using VS 2017 target 4.7.2

**Comment by jjziets** [comment]
nope. the same issue. stuck in that T

**Comment by jjziets** [comment]
@jjxtra Im sure I making a small mistake.

**Comment by jjziets** [comment]
Looks like it is a compatibility issue between ES and windowsforums. running the same code in console app works fine.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ExchangeSharp;

namespace WindowsFormsApp5
{
    public partial class Form1 : Form
    {
        private ExchangeCryptopiaAPI cryptopiaAPI = new ExchangeCryptopiaAPI();
        private Timer TimerRefresh;

        public Form1()
        {
            InitializeComponent();
            this.Text = Application.ProductName + " [v" + Application.ProductVersion + "]";

        }

        private void button1_Click(object sender, EventArgs e)
        {
            try
            {
                Dictionary<string, decimal> balances = cryptopiaAPI.GetAmountsAsync().Sync();
                ExchangeTicker ticker = cryptopiaAPI.GetTickerAsync("BTC_USD").Sync();


                ExchangeOrderBook OB = cryptopiaAPI.GetOrderBookAsync("BTC_USD", 1).Sync();

                string stats = "BTC Bid: " + ticker.Bid.ToString() + " Ask: " + ticker.Ask.ToString() + " Last trade: " + ticker.Last.ToString();


                foreach (KeyValuePair<string, decimal> entry in balances)
                {

                    stats += " " + entry.Key + " " + entry.Value.ToString();

                }
                toolStripStatusLabel1.Text = stats;

            }
            catch
            {
                toolStripStatusLabel1.Text = "Error updating status bar";
            }
            finally
            {

            }
        }
    }
}

**Comment by kingchenc** [comment]
@jjxtra is there some workaround for windows forms for the hanging bug?

**Comment by jjxtra** [comment]
Please use async and await...
