### ISSUE TITLE
Signature verification failed in Kucoin

### ISSUE THREAD

**Issue by ahvahsky2008** [jjxtra/ExchangeSharp#324]
I use this code
```
IExchangeAPI eapi = new ExchangeKucoinAPI();
eapi.LoadAPIKeysUnsecure("5c1608855fb02358f2337861", "817fb3f1-92fd-4600-ad9c-c7b3128f724f");
var res = eapi.GetAmountsAsync().Result;
```
Its raise error
**Signature verification failed**

**Comment by vslee** [comment]
Thanks for filing this bug. If you send a pull request with the solution, we'll be happy to merge it. If you don't know how, you can also post the updated code here.

**Comment by jjxtra** [comment]
Closing old issues, someone can submit pr if this is still an issue
