### ISSUE TITLE
1013 "Invalid Price" BinanceApi LimitOrderRequest error

### ISSUE THREAD

**Issue by Caider08** [jjxtra/ExchangeSharp#334]
I have no problems when placing "Market" orders through the api but when I go to place orders as "Limit" I get invalid price every time (have tried placing the same orders manually with no problems).
My guess at this point is it has something to do with needing to specify "timeInForce"?
How do I pass that in through the "ExtraParameters" of ExchangeOrderRequest()?

Thanks!

**Comment by Caider08** [comment]
I created ExchangeOrderRequestMINE : ExchangeOrderRequest 
public string TimeInForce  { get; set; } AND then pass "GTC" in to that parameter when creating an order.
The above gets MOST to work as limit orders now but this type of scenario happens:
REP/BTC and WAVES/BTC pairs failed WHILE POWR/BTC and LINK/BTC were successful (on same run).
Any ideas ?

**Comment by Caider08** [comment]
It appears it's the coins that don't have 8 decimal places in their pricing.
I have tried everyway I can think of to round to 7 or 6 decimal places depending on the coin but I'm still getting the "Invalid price".
I even tried to manually construct the order on a couple coins to test it but still errors.
When using the same prices and same amounts MANUALLY through the client it works no problems.

**Comment by Caider08** [comment]
Fixed this limit order problem by creating my own BinanceAPIclass and inheriting the base class from ExchangeSharp.  Inside my class I altered the amounts/price for the PlaceOrderAsync() method.

**Comment by justinr636** [comment]
Hey @Caider08 , I've come across the same issue and came to similar conclusions as you have, but I'm having trouble fixing it.

Would you mind sharing some code snippets or more information as to how you resolved it?

**Comment by justinr636** [comment]
Updating ExchangeSharp to 0.5.9 seemed to resolve the issue for me. No need to add the extra parameters or round the prices/amounts.

I think it is safe to close this issue.
