### ISSUE TITLE
ExchangeBitfinexAPI GetOrderBook uses wrong parameter name

### ISSUE THREAD

**Issue by BobDeCuir** [jjxtra/ExchangeSharp#341]
In the ExchangeBitfinexAPI.cs file, line 320: uses "len" to limit the max_count. The API has apparently changed and "len" is no longer supported. The correct parameter is as follows:

decimal[][] books = await MakeJsonRequestAsync<decimal[][]>("/book/t" + marketSymbol + "/P0?limit_bids=" + maxCount + "limit_asks=" + maxCount);

Instead of:

decimal[][] books = await MakeJsonRequestAsync<decimal[][]>("/book/t" + marketSymbol + "/P0?len=" + maxCount);

My apologies for not doing a proper GitHub request. Visual Studio is acting up submitting to the site.

Bob DeCuir

**Comment by jjxtra** [comment]
Fixed.
