### ISSUE TITLE
TuxExchangeAPI GetRecentTrades wrong Jtoken being parsed

### ISSUE THREAD

**Issue by BobDeCuir** [jjxtra/ExchangeSharp#342]
ExchangeTuxExchangeAPI.cs, Line 167, the foreach loop parses the wrong JToken and should read:

foreach (JToken trade in token)
 trades.Add(trade.ParseTrade("amount", "rate", "type", "date", TimestampType.Iso8601, "tradeid"));

Instead of : 
   foreach (JToken trade in token)
   trades.Add(token.ParseTrade("amount", "rate", "type", "date", TimestampType.Iso8601, "tradeid"));

TuxExchange is still wonky returning Trades, and it seldom works correctly - so this was easy to miss if it does.

Bob

**Comment by jjxtra** [comment]
I'm not seeing a difference in the two code snippets

**Comment by BobDeCuir** [comment]
**trade**.ParseTrade vs **token**.ParseTrade

**Comment by jjxtra** [comment]
Allright thanks fixed :)
