### ISSUE TITLE
BlueTrade 

### ISSUE THREAD

**Issue by BobDeCuir** [jjxtra/ExchangeSharp#344]
in ExchangeBleutradeAPI.cs

OnGetAmounts() and OnGetAmountsAvailabletoTrade()

The foreach uses the wrong token.

LINES 209 & 222

 foreach (JToken token in result)
 {
                decimal amount = result["Balance"].ConvertInvariant<decimal>();
                if (amount > 0) amounts[token["Currency"].ToStringInvariant()] = amount;
 }

should be:

                decimal amount = token["Balance"].ConvertInvariant<decimal>();

**Comment by RapidEU** [comment]
It is fixed as I can see... @jjxtra close this if you can.
