### ISSUE TITLE
Add support for getting Funding wallet addresses in Bitfinex

### ISSUE THREAD

**Issue by chriswhellams** [jjxtra/ExchangeSharp#346]
The Bitfinex API implementation is hardcoded to use the exchange wallet to get an address. I would like to extend this to support returning addresses for the Bitfinex funding wallet. Given that the GetAddress method is in the ExchangeAPI and is common to all Exchange implementation I'm just wondering what the best way to implement this would be ? The two simple options I see are 

1. Add a new method only to the BitfinexAPI code to expose this
2. Add an optional parameter to GetDepositAddressAsync allowing the wallet name to be specified

e.g.
`public virtual async Task<ExchangeDepositDetails> GetDepositAddressAsync(string currency, bool forceRegenerate = false, walletName = "")`

Neither feels like a great option. I'm happy to make the change and submit the PR but would welcome any comments or suggestions on the best way to implement this.

**Comment by jjxtra** [comment]
Closing old issues, someone can submit pr if this is still an issue
