### ISSUE TITLE
RequestTimeout doesn't work sometimes

### ISSUE THREAD

**Issue by kcabrera99** [jjxtra/ExchangeSharp#348]
api.RequestTimeout property doesn't always work.  Sometimes I get an exception but other times it just hangs.

**Comment by pixel75** [comment]
same to me. with version .58 no issues like these

**Comment by jjxtra** [comment]
If anyone has a reproducible scenario happy to take a look...

**Comment by jjxtra** [comment]
Please let me know if 0.6.0 has the problem.
