### ISSUE TITLE
Kucoin API has been updated

### ISSUE THREAD

**Issue by kcabrera99** [jjxtra/ExchangeSharp#350]
The Kucoin API was updated recently and now the API calls aren't working.

**Comment by jjxtra** [comment]
You are welcome to submit a pull request if you would like to fix this

**Comment by username77** [comment]
> The Kucoin API was updated recently and now the API calls aren't working.

try to use this api: https://github.com/mscheetz/KuCoinApi.Net/tree/v2.0

**Comment by jjxtra** [comment]
If someone wants to create a pr with that KuCoinApi.Net project I will happily merge it in

**Comment by kcabrera99** [comment]
I'm trying to do a pull request on exchangesharp but it's not letting me.

**Comment by username77** [comment]
> I'm trying to do a pull request on exchangesharp but it's not letting me.

post the code here

**Comment by vslee** [comment]
To create a pull request, you have to fork the repository first. Then on your fork, create a new branch and commit your changes there. Then, go back to github and view your fork, there will be a button to create a pull request. Here are detailed instructions (but it doesn't have to be as complicated as these instructions) https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

Or, if you want, you can just post the new code here on this thread and someone will probably create the pull request for you.

**Comment by vslee** [comment]
I created the first pull request to help you get started

**Comment by kcabrera99** [comment]
I was able to update the getcandles method but I'm having trouble with the private apis.  Getting an error about the signature.  "Invalid KC-API-SIGN"

**Comment by kcabrera99** [comment]
I think I got it now

**Comment by kcabrera99** [comment]
Got most of the gets working, but can't get past the "Invalid KC-API-SIGN" errors for the POST requests.

**Comment by vslee** [comment]
It likely has something to do with signing the message: https://docs.kucoin.com/#signing-a-message

**Comment by kcabrera99** [comment]
I've been looking at that all day trying to get it to work.

**Comment by vslee** [comment]
Okay, just make a pull request with what you have so far and I'll take a look

**Comment by kcabrera99** [comment]
OK, I think I created the pull request.  I was able to get the post requests working for place order.  I had to change the contenttype to application/json.

I have tested getcandles, placeorder, getorderdetails which calls getopenorders and getcompletedorders.  

Kucoin now offers a way to get the details for a specific orderID but I did not have time to implement that.  Also, I changed the getnonceoffset to use a timestamp function that they now offer instead of getting the tickers. 

Kucoin requires a clientOid which is a GUID even though in some parts of their documentation it says it is optional.  I am just creating a new GUID when I place an order since the orderID that is created by the exchange is returned when an order is placed.

CancelOrder doesn't work.  It fails when calling getorderdetails  which is weird because that call works fine if I call the method directly.

**Comment by vslee** [comment]
See our comments on the PR

**Comment by ryanfalzon** [comment]
Has anyone encountered an issue with KuCoin's new API when calling the '/api/v1/accounts' GET endpoint. It is giving me an empty list as a result. Obviously this does not make sense as I am sure that I have balances on KuCoin!

**Comment by username77** [comment]
Move coins from main to trade account before.

**Comment by BobDeCuir** [comment]
ExchangeKucoinAPI.cs Line 170 "OnGetOrderbookAsync" has an invalid character ("&" should be "?"). The line should be:

JToken token = await MakeJsonRequestAsync<JToken>("/market/orderbook/level2_" + maxCount + "?symbol=" + marketSymbol);

ALSO - This method only supports "level2_20" or "level2_100". Any other maxCount value will fail.

**Comment by jjxtra** [comment]
Please submit PR
