### ISSUE TITLE
Requesting Hitbtc Websocket APIs

### ISSUE THREAD

**Issue by mohanc4547** [jjxtra/ExchangeSharp#355]
Of the Websocket functions available with hitbtc, can we please have the ongettradesasync functionality implemented. 
Its following the same pattern as of ZBcom as i see, i tried to implement, but couldnt get through the 500 Error.

**Comment by jjxtra** [comment]
You are welcome to submit a pull request when you get it working.

**Comment by mohanc4547** [comment]
> You are welcome to submit a pull request when you get it working.

Is it the 500 error that you also were not able to get pass through ? please let me know
