### ISSUE TITLE
New Kraken symbols 

### ISSUE THREAD

**Issue by BobDeCuir** [jjxtra/ExchangeSharp#363]
Kraken has added new Symbols and Market Pairs. The new Markets are not listed in the table lookup, so the lookup will fail for many Markets. Here is a comprehensive list of all Markets on Kraken...

/// <summary>
/// Change Kraken symbols to more common sense symbols
/// </summary>
private static readonly IReadOnlyDictionary<string, string> exchangeSymbolToNormalizedSymbol = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        { 
            { "ADAUSD", "adausd" },
            { "ADAEUR", "adaeur" },
            { "ADAXBT", "adabtc" },
            { "ADACAD", "adacad" },
            { "ADAETH", "adaeth" },
            { "BCHEUR", "bcheur" },
            { "BSVEUR", "bsveur" },
            { "BSVUSD", "bsvusd" },
            { "BSVXBT", "bsvbtc" },
            { "BCHUSD", "bchusd" },
            { "BCHXBT", "bchbtc" },
            { "DASHEUR", "dasheur" },
            { "DASHUSD", "dashusd" },
            { "DASHXBT", "dashbtc" },
            { "EOSETH", "eoseth" },
            { "EOSEUR", "eoseur" },
            { "EOSUSD", "eosusd" },
            { "EOSXBT", "eosbtc" },
            { "GNOETH", "gnoeth" },
            { "GNOUSD", "gnousd" },
            { "GNOEUR", "gnoeur" },
            { "GNOXBT", "gnobtc" },
            { "QTUMEUR", "qtumeur" },
            { "QTUMCAD", "qtumcad" },
            { "QTUMUSD", "qtumusd" },
            { "QTUMXBT", "qtumbtc" },
            { "QTUMETH", "qtumeth" },
            { "USDTZUSD", "usdtusd" },
            { "XTZETH", "xtzeth" },
            { "XTZUSD", "xtzusd" },
            { "XTZEUR", "xtzeur" },
            { "XTZCAD", "xtzcad" },
            { "XTZXBT", "xtzbtc" },
            { "XETCXETH", "etceth" },
            { "XETCXXBT", "etcbtc" },
            { "XETCZEUR", "etceur" },
            { "XETCZUSD", "etcusd" },
            { "XETHXXBT", "ethbtc" },
            { "XETHXXBT.d", "ethbtc" },
            { "XETHZCAD", "ethcad" },
            { "XETHZCAD.d", "ethcad" },
            { "XETHZEUR", "etheur" },
            { "XETHZEUR.d", "etheur" },
            { "XETHZGBP", "ethgbp" },
            { "XETHZGBP.d", "ethgbp" },
            { "XETHZJPY", "ethjpy" },
            { "XETHZJPY.d", "ethjpy" },
            { "XETHZUSD", "ethusd" },
            { "XETHZUSD.d", "ethusd" },
            { "XICNXETH", "icneth" },
            { "XICNXXBT", "icnbtc" },
            { "XLTCXXBT", "ltcbtc" },
            { "XLTCZEUR", "ltceur" },
            { "XLTCZUSD", "ltcusd" },
            { "XMLNXETH", "mlneth" },
            { "XMLNXXBT", "mlnbtc" },
            { "XREPXETH", "repeth" },
            { "XREPXXBT", "repbtc" },
            { "XREPZUSD", "repusd" },
            { "XREPZEUR", "repeur" },
            { "XXBTZCAD", "btccad" },
            { "XXBTZCAD.d", "btccad" },
            { "XXBTZEUR", "btceur" },
            { "XXBTZEUR.d", "btceur" },
            { "XXBTZGBP", "btcgbp" },
            { "XXBTZGBP.d", "btcgpb" },
            { "XXBTZJPY", "btcjpy" },
            { "XXBTZJPY.d", "btcjpy" },
            { "XXBTZUSD", "btcusd" },
            { "XXBTZUSD.d", "btcusd" },
            { "XXDGXXBT", "dogebtc" },
            { "XXLMXXBT", "xlmbtc" },
            { "XXLMZUSD", "xlmusd" },
            { "XXLMZEUR", "xlmeur" },
            { "XXMRXXBT", "xmrbtc" },
            { "XXMRZEUR", "xmreur" },
            { "XXMRZUSD", "xmrusd" },
            { "XXRPXXBT", "xrpbtc" },
            { "XXRPZEUR", "xrpeur" },
            { "XXRPZUSD", "xrpusd" },
            { "XXRPZCAD", "xrpcad" },
            { "XXRPZJPY", "xrpjpy" },
            { "XZECXXBT", "zecbtc" },
            { "XZECZEUR", "zeceur" },
            { "XZECZJPY", "zecjpy" },
            { "XZECZUSD", "zecusd" }
        };

**Comment by RapidEU** [comment]
I added a PR for that.
