### ISSUE TITLE
BitBank Market Symbol Separator is wrong character

### ISSUE THREAD

**Issue by BobDeCuir** [jjxtra/ExchangeSharp#364]
ExchangeBitBankAPI.cs Line 33

The BitBank Separator is "-", not "_"

Line should read:
MarketSymbolSeparator = "-";

**Comment by vslee** [comment]
I think Jeff is a bit tied up with other projects these days to keep up with these changes. He's pretty responsive w/ pull requests though, so if you send a PR, he'll probably merge it.

**Comment by RapidEU** [comment]
Are you sure?
Looking out at https://docs.bitbank.cc/#!/Ticker/ticker
it looks like it is '_'.

**Comment by jjxtra** [comment]
Please submit PR
