### ISSUE TITLE
Huibi Market Symbols don't parse

### ISSUE THREAD

**Issue by BobDeCuir** [jjxtra/ExchangeSharp#369]
Huobi is tricky to get working. Most interaction in the US is on Huobi.com. HuiboPro is Chinese only. If your keys were created on Huobi.com - the default API url values must be changed. They also have a 3rd site (HBG.com) and the same applies.

That being said, not all market pairs are 6 characters, so if you try to go from ExchangeMarket to GlobalMarket for all returned pairs, exceptions are thrown. I managed to parse out all market symbols for both sites using the following code: ExchangeHuobiAPI.CS Line ~45

public override string ExchangeMarketSymbolToGlobalMarketSymbol(string marketSymbol)
        {
            // There are four markets for HuobiPro.com: USDT, HUSD, BTC, ETH, and HT. Huobi.com adds another USD Market
            // All market pairs end with these
            int pos, length = marketSymbol.Length;
            if (marketSymbol.EndsWith("usdt") || marketSymbol.EndsWith("husd")) pos = 4;
            else if (marketSymbol.EndsWith("btc") || marketSymbol.EndsWith("eth") || marketSymbol.EndsWith("usd")) pos = 3;
            else if (marketSymbol.EndsWith("ht")) pos = 2;
            else throw new ArgumentException("Invalid market symbol " + marketSymbol);
            return ExchangeMarketSymbolToGlobalMarketSymbolWithSeparator(marketSymbol.Substring(0, length - pos) + GlobalMarketSymbolSeparator + marketSymbol.Substring(length - pos, pos), GlobalMarketSymbolSeparator);
        }

**Comment by BobDeCuir** [comment]
For anyone implementing Huobi in the US - these are the correct urls:

public override string BaseUrl { get; set; } = "https://api.huobi.com";
public string BaseUrlV1 { get; set; } = "https://api.huobi.com/v1";
public override string BaseUrlWebSocket { get; set; } = "wss://api.huobi.pro/hbus/ws";
public string PrivateUrlV1 { get; set; } = "https://api.huobi.com/v1";

**Comment by jjxtra** [comment]
Please submit PR
