### ISSUE TITLE
Huobi Order Result Parsing misspelling

### ISSUE THREAD

**Issue by BobDeCuir** [jjxtra/ExchangeSharp#370]
Houbi Order Results do not calculate Amounts Filled because of a spelling error. Also, Fees are returned by the Exchanged, but not included in the parsing.

ExchangeHuobiAPI.cs Line: ~875
AmountFilled = token["field-amount"].ConvertInvariant<decimal>(),
should be
AmountFilled = token["filled-amount"].ConvertInvariant<decimal>(),

    ExchangeOrderResult result = new ExchangeOrderResult()
            {
                OrderId = token["id"].ToStringInvariant(),
                MarketSymbol = token["symbol"].ToStringInvariant(),
                Amount = token["amount"].ConvertInvariant<decimal>(),
                AmountFilled = token["filled-amount"].ConvertInvariant<decimal>(),
                Fees = token["filled-fees"].ConvertInvariant<decimal>(),
                Price = token["price"].ConvertInvariant<decimal>(),
                OrderDate = CryptoUtility.UnixTimeStampToDateTimeMilliseconds(token["created-at"].ConvertInvariant<long>()),
                IsBuy = token["type"].ToStringInvariant().StartsWith("buy"),
                Result = ParseState(token["state"].ToStringInvariant()),
            };

**Comment by jjxtra** [comment]
Please submit PR

**Comment by BobDeCuir** [comment]
Regarding this fix:

Huobi and HuobiPro are two different endpoints, and the APIs have diverged. For HuobiPro, this fix does not apply. The original JSON names were correct ("field-" not "filled-"). Apparently, this was a misspelling on the original site (now HuobiPro), that was corrected on the newer US Site (Huobi).

What I had to do was create two Exchanges (ExchangeHuobiAPI.cs and ExchangeHuobiProAPI.cs) and switch accordingly. I don't know how you wish to handle this.

Creating PRs on Git has been problematic for me. It requires maintaining multiple versions of the library because I'm not using NuGet and use a custom build internally. I'll give it another shot with the better Git support on VS2019. Thanks for the updates.

**Comment by BobDeCuir** [comment]
Finally, both endpoints support GetRecentTrades, but this wasn't implemented in the API. If you want to add it, it's simply:

        protected override async Task<IEnumerable<ExchangeTrade>> OnGetRecentTradesAsync(string marketSymbol)
        {
            /*{[ {"id": "10073445391028249027265","amount": 0.0011,"price": 4132.73,"direction": "buy","ts": 1554098193868},   ...    ]}  */
            List<ExchangeTrade> tradeList = new List<ExchangeTrade>();

            string url = "/market/history/trade?symbol=" + marketSymbol + "&size=100";
            JToken trades = await MakeJsonRequestAsync<JToken>(url, BaseUrl, null);
            foreach(var token in trades)
            {
                foreach(var data in token["data"]) tradeList.Add(data.ParseTrade("amount", "price", "direction", "ts", TimestampType.UnixMilliseconds, null ));  // ID is provided but exceeds long, so we will discard
            }
            return tradeList;
        }
