### ISSUE TITLE
Bittrex json format

### ISSUE THREAD

**Issue by ahvahsky2008** [jjxtra/ExchangeSharp#371]
Bittrex return this json string. How decode param **G**? Its not gzip string
`{"C":"d-88903F9C-uIVg,2|Cv,81594","G":"f8N0wWnjI7HYfemJI8e0xCbSANWfxnpNCIT4iAHhWDhZjpcgeesgN6r5uUtMrGXJhuLnOyMI52yEsxDhlxcpAJc6+oPWpOx4b7k2EWza50QZM5sNKXQHzanncDgQPzJQc7yWAg==","M":[]}
`

**Comment by jjxtra** [comment]
More details please, what end point, etc.?

**Comment by ahvahsky2008** [comment]
Firstly i send 
```
.Send("{\"H\":\"c2\",\"M\":\"QueryExchangeState\",\"A\":[\"USDT-BTC\"],\"I\":2}");
.Send("{\"H\":\"c2\",\"M\":\"SubscribeToExchangeDeltas\",\"A\":[\"USDT-BTC\"],\"I\":1}");

```
After i receive json from socket. All works, but sometimes bittrex return non-gzipped data, ex:
```
{"C":"d-24015234-QtKZ,2|Cp,2F6CF","G":"LZuWgEqIuFTqnxXJlAFNIDR98unn58WPVjcbmli6eW+ih/aLkLFJJLvagY23nHQo/VmPjARX1nVLQ4LkomKMsx9IBRWwqGTexcXar7nQYrDkiUO84q5E2+aLGAZlHW7NqCepKw==","M":[]}
{"R":true,"I":"1"}
```

**Comment by vslee** [comment]
Thanks for filing this bug. If you send a pull request with the solution, we'll be happy to merge it. If you don't know how, you can also post the updated code here.

**Comment by jjxtra** [comment]
Closing old issues, someone can submit pr if this is still an issue
