### ISSUE TITLE
Binance "Last completed order" bug

### ISSUE THREAD

**Issue by MachineTrader** [jjxtra/ExchangeSharp#377]
var LastCompletedTrade = Api.GetCompletedOrderDetailsAsync(Pair).Sync().First();

Doesn't seem to work for Binance. Just getting 0 back, even though a trade was filled recently.(within an hour)
The same code works on Cryptopia.
Any clue why?

Update:
Ok I've experimented some more, and it shows that all last trades are retrieved, but the .AveragePrice is always 0, but instead .Price has the value I'm looking for. Inconsistent I guess to Cryptopia. But if that is an exchange thing or a thing that should be changed in this library. I don't know.

Secondly, it doesn't return only filled orders, it also returns cancelled orders, which is not what the function name implies.

**Comment by RapidEU** [comment]
Return data is not something ExchangeSharp generate, it is based on the Exchange API.

Other than that, you can easily LINQ to filter the results where the OrderType is Canceled probably.

Paste a copy of your code sample maybe I could help you. (Even thought I dont see in binance API that they return if it was canceled or not)

I'm implementing the UserDataWebSocket so you can get the actions that are happening right away. and you could stack it up in a list or something to have previous deals (in the current session)

**Comment by MachineTrader** [comment]
This is the code I'm using to get the latest orders. I figured a away to filter out non filled orders.
But for some reason I can not get the api to give me the latest trades. Sometimes the latest trade is many days old. [https://1drv.ms/u/s!ArAeE5D8G2U5gupUUd91hWdb-s4AVQ](url)
` 
  private decimal GetLastTrade()
        {
            var ViewOrdersAfterThisTime = DateTime.Now.AddDays(-10);
            var LastTrades = Api.GetCompletedOrderDetailsAsync(Pair, ViewOrdersAfterThisTime).Sync();
            
            //Create a new list for filled orders
            List<ExchangeOrderResult> LastCompletedTrades = new List<ExchangeOrderResult>();

           //Since api returns all last orders inclusive cancelled. Filtering needs to be done.
           foreach (var Trades in LastTrades)
                  if (Trades.Result == ExchangeAPIOrderResult.Filled)
                          LastCompletedTrades.Add(Trades);
                            
           
  //If nothing is received, make an empty place in the list.
            if (LastCompletedTrades.Count == 0)  LastCompletedTrades.Add(new ExchangeOrderResult {Price= 0.0m});

            //Binance only returns a price if it was a limit order.
            Console.Write($"\n{LastCompletedTrades.Last()} Price:{LastCompletedTrades.Last().Price} Avg:{LastCompletedTrades.Last().AveragePrice} ");

            //RETURN THE PRICE THAT HAS A VALUE
            if (LastCompletedTrades.Last().Price > 0) return (LastCompletedTrades.Last().Price);
            if (LastCompletedTrades.Last().AveragePrice > 0) return(LastCompletedTrades.Last().AveragePrice);
            else return (0m);
        }`

**Comment by MachineTrader** [comment]
Issue solved. 
It seems all the issues I had were related to the Nuget package version.
The problem was that I was trying to print the orders from the last 10 days, and if that were more than a certain number, it would just stop returning the last ones.

Most people are on Binance I guess, so this update is an urgent one to push out as a package.
