### ISSUE TITLE
Unable to get funding ticker for bitfinex, due to hardcoded values.

### ISSUE THREAD

**Issue by dave7280** [jjxtra/ExchangeSharp#384]
As you might know or not, bitfinex also supports lending of currencies such as BTC or USD.
It supports fetching current lending rates using ticker symbols eg:

fUSD
fBTC

while the trading pairs are recognized as:

tBTCUSD
tETHUSD

If i understand the code correctly, current implementation of the code, HARDCODES trading pairs as only choice. This way it's impossible to fetch lending rates.

```
 protected override async Task<ExchangeTicker> OnGetTickerAsync(string marketSymbol)
        {
            JToken ticker = await MakeJsonRequestAsync<JToken>("/ticker/t" + marketSymbol);
            return this.ParseTicker(ticker, marketSymbol, 2, 0, 6, 7);
        }

```

> "/ticker/t"

Can you remove the hardcoding to allow fetching rates for any symbols including lending rates?

https://api.bitfinex.com/v2/ticker/fBTC
https://api.bitfinex.com/v2/ticker/tBTCUSD

**Comment by jjxtra** [comment]
It is not easy to fit this into current architecture which wants an actual market symbol, so I suggest to you to make an extension method of the Bitfinex API that makes a json request and parses the result manually. Make it called GetTickerFundingAsync or something...
