### ISSUE TITLE
I'm receiving an unusual value from BitMEX GetAmountsAsync

### ISSUE THREAD

**Issue by PSinke** [jjxtra/ExchangeSharp#395]
I am calling GetAmountsAsync on the exchangeApi for BitMEX and receive the following dictionary<string, decimal> : XBT, 70000
I wish there were 70000 XBT in my account there, but there are not :) there are only 0.0007. Is this a bug in retrieving the values from BitMEX?  Other exchanges do give the right amounts when calling 
GetAmountsAsync. 

I could easily add an exception here, but wanted to check first.

**Comment by jjxtra** [comment]
You can send some to the donation address if you want, that is a lot of BTC :)

Is Bitmex showing other coins with similar multipliers? Maybe they are measured in satoshi? Some setting on your account?

**Comment by PSinke** [comment]
I would it it were true, for sure :)

I just had a look at their API Explorer, at https://www.bitmex.com/api/explorer/#!/User/User_getWallet
and that also returns 70000 as the amount. So it looks like the 'amount' value needs to divided by 10000000 to get the correct amount (0.0007). I cannot find any info on this though. 
I take it you haven't heard from anyone else that this value is received incorrectly?

**Comment by jjxtra** [comment]
You are the first one to bring this up.

**Comment by vslee** [comment]
Thanks for filing this bug. If you send a pull request with the solution, we'll be happy to merge it. If you don't know how, you can also post the updated code here.

**Comment by jjxtra** [comment]
Closing old issues, someone can submit pr if this is still an issue
