### ISSUE TITLE
OnGetOrderBookWebSocket

### ISSUE THREAD

**Issue by liuqiba** [jjxtra/ExchangeSharp#396]
BitMex api,  OnGetOrderBookWebSocket have not set OrderBook SequenceId .Maybe web socket data send first then get second.I fund some times bid1 or ask1 not refresh. Now I use "orderBook10" replace "orderBookL2"

**Comment by vslee** [comment]
If you send a pull request with the fix, we would be happy to merge it. If you don't know how, you can post the fixed version of the code here.

**Comment by jjxtra** [comment]
This appears resolved on their end, open it back up if you see it again
