### ISSUE TITLE
CancelOrderAsync() error and overall API slowness

### ISSUE THREAD

**Issue by ferib** [jjxtra/ExchangeSharp#397]
``
var orders = await KucoinApi.GetOpenOrderDetailsAsync(Coinpair);
foreach(var order in orders)
    await KucoinApi.CancleOrderAsync(order.OrderId);
``

When i do like this, i sometimes get an error on `CancleOrderAsync` with 'Input string was not in a correct format.'.
Sometimes i don't get an error but the order wont be removed.

i also noticed that the API is stuck after 10-20 API calls and that i have to wait like 30 seconds until i can continue sending API requests, i don't know if this has anything to do with the API or KuCoin itself. (KuCoin says max 50.000 API calls within 5min)

**Comment by ferib** [comment]
UPDATE: to fix this issue, use the API like this ``KucoinApi.CancleOrderAsync(order.OrderId, order.MarketSymbol);``
_should fix the transaction issue, but still slow API?_

**Comment by vslee** [comment]
Thanks for clarifying usage of CancelOrderAsync() on Kucoin. 
As for the slow API, if you send a pull request with the solution, we'll be happy to merge it. If you don't know how, you can also post the updated code here.

**Comment by jjxtra** [comment]
Is this a problem with slow API on their end or a problem where exchange sharp gets a result quickly and then barfs or chugs on it too slowly?

**Comment by jjxtra** [comment]
You are probably running into rate gate issue, you can configure it to allow more requests if you like.
