### ISSUE TITLE
gdax private api

### ISSUE THREAD

**Issue by zachtdavis** [jjxtra/ExchangeSharp#4]
me again, id happily throw you an LTC tip if you could implement the private side of gdax (mainly the place order, get open orders, and cancel orders).

Thanks either way :)

**Comment by jjxtra** [comment]
I'll get started, any donation is appreciated at Litecoin address:
Lc42Z2SS7RDjz8nzbnmdBtLrQGLkVSyToB

Jeff Johnson
CEO / CTO, Digital Ruby, LLC

**Comment by jjxtra** [comment]
This has been pushed to master and a new nuget package created. If it helps with your donation this took me 2.5 hours to complete. Thanks again, and good luck with your trading! Let me know if you need anything else.
