### ISSUE TITLE
Okex GetOrderBookWebSocket only works for swap symbols

### ISSUE THREAD

**Issue by vlebedev7** [jjxtra/ExchangeSharp#402]
On [this line](https://github.com/jjxtra/ExchangeSharp/blob/360e0e069e2dca9dcd89e19e8ca8c64457b02f14/ExchangeSharp/API/Exchanges/Okex/ExchangeOkexAPI.cs#L239) you can see that Okex orderbook WS-channel is created as "swap/depth:{0}-SWAP", which only works for swap symbols. For spot symbols you need to use "spot/depth:{0}". 
In [the recent PR](https://github.com/jjxtra/ExchangeSharp/pull/400) "swap" is simply replaced with "spot" in another method, should I do the same? Or it's better to make a common solution, for example we can use {0}-SWAP as symbol string for swap symbols and the code will relplace "spot/" to "swap/" depending on the existense of -SWAP ending

**Comment by vslee** [comment]
Good point, we should modify the OnGetMarketSymbolsMetadataAsync() so that it returns all symbols including Tokens, Futures, and Perpetual Swaps, instead of only Tokens as it is now. Then, we can modify both the Orderbook WS and Trades WS so that they can accept SPOT or SWAP.

**Comment by vslee** [comment]
If you want to take a shot at it, I'll review it for you.
