### ISSUE TITLE
Binance authentication problem because of recvWindow

### ISSUE THREAD

**Issue by RaoulJacobs** [jjxtra/ExchangeSharp#419]
Hi 

Binance has updated their api and since i'm experiencing a problem with authenticating signed endpoints.
the 1st issue was that the recvWindows shouldn't me larger then 60000 ticks.
I have already updated the RequestWindow as per below, but then I get an error that timestamp is too much off from the server time.
Anyone any suggestions?

```
public ExchangeBinanceAPI()
        {
            // give binance plenty of room to accept requests
            RequestWindow = TimeSpan.FromTicks(60000); 
```

**Comment by vslee** [comment]
I don't have a Binance account so I can't help you debug. But you do figure out the solution, please post it here and we'll incorporate it.

**Comment by RaoulJacobs** [comment]
@vslee I found it:
the NonceOffset should also be set to 0

`RequestWindow = TimeSpan.FromTicks(60000); 
            NonceStyle = NonceStyle.UnixMilliseconds;
            NonceOffset = TimeSpan.FromSeconds(0.0);
            `

**Comment by RaoulJacobs** [comment]
@vslee final version of instantiation ExchangeBinanceApi handling the NonceOffset and RequestWindow (vrecWindow)
`public ExchangeBinanceAPI()
        {
            // give binance plenty of room to accept requests
            RequestWindow = TimeSpan.FromMilliseconds(60000);  // 60000 is max value = max request time window of 60 seconds
            NonceStyle = NonceStyle.UnixMilliseconds;
            NonceOffset = TimeSpan.FromSeconds(15); // 15 seconds are deducted from current UTCTime as base of the request time window
            MarketSymbolSeparator = string.Empty;
            WebSocketOrderBookType = WebSocketOrderBookType.DeltasOnly;
        }`
