### ISSUE TITLE
Please update NuGet package again - its 3 months old

### ISSUE THREAD

**Issue by GonzoKK** [jjxtra/ExchangeSharp#420]
Please update again - its 3 months old

![image](https://user-images.githubusercontent.com/38913162/63148979-13bb7d00-c003-11e9-92bf-0c9751809fe0.png)

_Originally posted by @GonzoKK in https://github.com/jjxtra/ExchangeSharp/issues/312#issuecomment-521906378_

**Comment by RapidEU** [comment]
@jjxtra I think it's up to u

**Comment by vslee** [comment]
Version 0.6.0.2 has now been released
