### ISSUE TITLE
ExchangeHuobiAPI.OnGetTickersAsync() - System.ArgumentException: 'Accessed JArray values with invalid key value: "data". Int32 array index expected.'

### ISSUE THREAD

**Issue by GonzoKK** [jjxtra/ExchangeSharp#421]
Possibly similar to https://github.com/jjxtra/ExchangeSharp/issues/415

![image](https://user-images.githubusercontent.com/38913162/63155550-09a17a80-c013-11e9-912e-985de6c3f544.png)

![image](https://user-images.githubusercontent.com/38913162/63155633-3f466380-c013-11e9-9bcb-86d59aafda7c.png)

{[
  {
    "open": 0.429192,
    "close": 0.43193,
    "low": 0.42868,
    "high": 0.444504,
    "amount": 805.14014476611283,
    "count": 2644,
    "vol": 349.6994085636,
    "symbol": "xmreth"
  },
  {
    "open": 8.158E-05,
    "close": 7.891E-05,
    "low": 7.814E-05,
    "high": 8.314E-05,
    "amount": 16773.64,
    "count": 4159,
    "vol": 1.3340653106,
    "symbol": "kmdbtc"
  },
  {
    "open": 1.72E-05,
    "close": 1.695E-05,
    "low": 1.681E-05,
    "high": 1.732E-05,
    "amount": 174810.79712369648,
    "count": 5410,
    "vol": 2.975608026,
    "symbol": "steembtc"
  },
  {
    "open": 1.098E-07,
    "close": 1.11E-07,
    "low": 1.086E-07,
    "high": 1.249E-07,
    "amount": 212304373.11159352,
    "count": 11322,
    "vol": 23.393710267908219,
    "symbol": "ncashbtc"

**Comment by GonzoKK** [comment]
I'll have a stab at troubleshooting this...

Firstly I removed "data" as its not there for this endpoint (see below)

![image](https://user-images.githubusercontent.com/38913162/63260483-58ece280-c281-11e9-89ad-9eabfaa02011.png)

Note that askKey and bidKey are hardcoded as null - which causes ParseTicker to crash on line 441

![image](https://user-images.githubusercontent.com/38913162/63261516-fe08ba80-c283-11e9-9eaf-8f4367994995.png)

https://api.huobi.pro/market/tickers
https://huobiapi.github.io/docs/spot/v1/en/#get-latest-tickers-for-all-pairs

This endpoint (for multiple tickers) returns:

"open": 0.429192,
"close": 0.43193,
"low": 0.42868,
"high": 0.444504,
"amount": 805.14014476611283,
"count": 2644,
"vol": 349.6994085636,
"symbol": "xmreth" 

Bid and Ask are not there, which means ParseTicker will fail.

Looks like the code would only work for a single ticker eg
https://api.huobi.pro/market/detail/merged?symbol=ethusdt

but not for multiple tickers...

A hack would be to test for null, but that means the ExchangeTicker would  be not be populated with Ask and Bid.

Any thoughts?

**Comment by vslee** [comment]
Might have to switch to get aggregated tickers endpoint bc that has bid/ask. 
GET https://api.huobi.pro/market/detail/merged

**Comment by vslee** [comment]
Yes, like you said, would work for only a single ticker not multiple. So we would have to loop through and call it multiple times if ppl wanted multiple tickers

**Comment by GonzoKK** [comment]
Testing further... I changed askKey to "ask" and bidKey to "bid"

![image](https://user-images.githubusercontent.com/38913162/63327465-8a6fb780-c32e-11e9-847f-36320211afaf.png)


This however leads to a parsing error for symbol "hb10":

  "symbol": "hb10",
  "open": 0.6076,
  "close": 0.608,
  "low": 0.6009,
  "high": 0.6147,
  "amount": 0.0,
  "count": 0,
  "vol": 0.0

![image](https://user-images.githubusercontent.com/38913162/63327730-0ec23a80-c32f-11e9-843a-4e27f07ad53d.png)

Seems the problem lies with api.ExchangeMarketSymbolToCurrencies(marketSymbol);

![image](https://user-images.githubusercontent.com/38913162/63328085-c7887980-c32f-11e9-9928-ed97706faa25.png)

I reckon the symbol parsing logic can/should be improved

**Comment by vslee** [comment]
What does hb10 refer to? Is that the name of a symbol?

**Comment by GonzoKK** [comment]
See https://github.com/jjxtra/ExchangeSharp/issues/424#issuecomment-523333243

**Comment by GonzoKK** [comment]
See potential fix at  https://github.com/jjxtra/ExchangeSharp/issues/424#issuecomment-528040380

**Comment by jjxtra** [comment]
Fixed in latest master
