### ISSUE TITLE
ExchangeKucoinAPI.OnGetTickersAsync() Line 188 - System.InvalidOperationException Cannot access child value on Newtonsoft.Json.Linq.JProperty.

### ISSUE THREAD

**Issue by GonzoKK** [jjxtra/ExchangeSharp#423]
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot access child value on Newtonsoft.Json.Linq.JProperty.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at ExchangeSharp.ExchangeKucoinAPI.<OnGetTickersAsync>d__17.MoveNext() in C:\!Dev\ExchangeSharp-master(6)\ExchangeSharp\API\Exchanges\Kucoin\ExchangeKucoinAPI.cs:line 188

![image](https://user-images.githubusercontent.com/38913162/63157407-2e97ec80-c017-11e9-8e17-c35d2302498f.png)

**Comment by vslee** [comment]
Thanks for filing this bug. If you could send a pull request with the solution, we'll merge it. If you don't know how, you can also post the updated code here.

**Comment by GonzoKK** [comment]
Easy fix...

![image](https://user-images.githubusercontent.com/38913162/64114011-2c11f280-cd8c-11e9-9ba2-f1a8e6e1a943.png)

```
protected override async Task<IEnumerable<KeyValuePair<string, ExchangeTicker>>> OnGetTickersAsync()
{
    List<KeyValuePair<string, ExchangeTicker>> tickers = new List<KeyValuePair<string, ExchangeTicker>>();
    // [ { "coinType": "KCS", "trading": true, "lastDealPrice": 4500, "buy": 4120, "sell": 4500, "coinTypePair": "BTC", "sort": 0, "feeRate": 0.001, "volValue": 324866889, "high": 6890, "datetime": 1506051488000, "vol": 5363831663913, "low": 4500, "changeRate": -0.3431  }, ... ]
    JToken token = await MakeJsonRequestAsync<JToken>("/market/allTickers");
    //foreach(JToken tick in token) {
    foreach(JToken tick in token["ticker"]) {
        string marketSymbol = tick["symbol"].ToStringInvariant();
        tickers.Add(new KeyValuePair<string, ExchangeTicker>(marketSymbol, ParseTickers(tick, marketSymbol)));
    }
    return tickers;
}
```

**Comment by GonzoKK** [comment]
FYI **token** variable = 

{{
  "ticker": [
    {
      "symbol": "LOOM-BTC",
      "high": "0.00000295",
      "vol": "23885.7388",
      "last": "0.00000292",
      "low": "0.00000284",
      "buy": "0.00000291",
      "sell": "0.00000292",
      "changePrice": "0",
      "averagePrice": "0.00000292",
      "changeRate": "0",
      "volValue": "0.069025547588"
    },
    {
      "symbol": "BCD-BTC",
      "high": "0.00006503",
      "vol": "370.12648309",
      "last": "0.00006442",
      "low": "0.00006273",
      "buy": "0.00006389",
      "sell": "0.0000645",
      "changePrice": "0.00000049",
      "averagePrice": "0.00006527",
      "changeRate": "0.0076",
      "volValue": "0.0236902261670466"
    },
