### ISSUE TITLE
Kraken GetTickersAsync Broken

### ISSUE THREAD

**Issue by GonzoKK** [jjxtra/ExchangeSharp#434]
Kraken's **GetTickersAsync** takes over 3 minutes and only returns 18 items (should be 82)  

Kraken is a bit complicated as certain symbols (but not all) have a X or Z prefix.

I'm gonna have a crack at fixing...

![image](https://user-images.githubusercontent.com/38913162/64363957-2cbbba80-d012-11e9-8ac1-5158deb8ecca.png)

**Comment by jjxtra** [comment]
I commited a fix, mostly it involved removing code which was nice

**Comment by GonzoKK** [comment]
Way quicker...

**Kraken**
 ✓ GetTickersAsync: 83 items [1,733s]
 ✓ GetCurrenciesAsync: 29 items [0,432s]
 ✓ GetMarketSymbolsAsync: 83 items [0,000s]
 ✓ GetMarketSymbolsMetadataAsync: 94 items [0,000s]
 🡆 QuoteCurrencies: "XETH", "XXBT", "ZCAD", "ZEUR", "ZGBP", "ZJPY", "ZUSD"
 🡆 SampleMarkets: "ADAETH", "ETCEUR", "REPETH", "XBTUSD", "XBTUSD.d", "XLMUSD"

**Comment by GonzoKK** [comment]
@jjxtra I see you also fixed ZB.com. Any thoughts on **Huobi**'s **GetTickersAsync**? https://github.com/jjxtra/ExchangeSharp/issues/421

**Huobi**
 ✗ GetTickersAsync: ERROR Accessed JArray values with invalid key value: "data". Int32 array index expected. [0,816s]
 ✓ GetCurrenciesAsync: 62 items [0,684s]
 ✓ GetMarketSymbolsAsync: 542 items [2,722s]
 ✓ GetMarketSymbolsMetadataAsync: 542 items [0,000s]
 🡆 QuoteCurrencies: "husd", "usdt", "btc", "eth", "trx", "ht"
 🡆 SampleMarkets: "aacbtc", "bttusdt", "cvnteth", "hcbtc", "mdseth", "wiccusdt"

**ZBcom**
 ✓ GetTickersAsync: 187 items [2,503s]
 ✗ GetCurrenciesAsync: ERROR The method or operation is not implemented. [0,000s]
 ✓ GetMarketSymbolsAsync: 187 items [0,000s]
 ✓ GetMarketSymbolsMetadataAsync: 187 items [0,836s]
 🡆 QuoteCurrencies: "usdt", "btc", "qc", "zb"
 🡆 SampleMarkets: "btc_qc", "eos_usdt", "ink_usdt", "qtum_qc", "snt_qc", "ytnb_usdt"

**Comment by jjxtra** [comment]
Probably a similar fix, hang on...

**Comment by jjxtra** [comment]
Checked in a fix/hack/workaround for huobi

**Comment by GonzoKK** [comment]
looks good, thanks

**Huobi**
 ✓ GetTickersAsync: 535 items [1,139s]
 ✓ GetCurrenciesAsync: 62 items [0,431s]
 ✓ GetMarketSymbolsAsync: 542 items [0,001s]
 ✓ GetMarketSymbolsMetadataAsync: 542 items [0,000s]
 🡆 QuoteCurrencies: "husd", "usdt", "btc", "eth", "trx", "ht"
 🡆 SampleMarkets: "ardreth", "creusdt", "dogebtc", "grseth", "uuueth", "wavesbtc"
