### ISSUE TITLE
Bithumb OnGetTickersAsync Broken

### ISSUE THREAD

**Issue by GonzoKK** [jjxtra/ExchangeSharp#436]
System.InvalidOperationException: 'Splitting Bithumb symbol 'BTC' with symbol separator '-' must result in exactly 2 pieces.'

Bithumb always defaults to **KRW** for the second currency (ie no splitting required)

![image](https://user-images.githubusercontent.com/38913162/64374528-57167380-d024-11e9-814b-1097a5c59f3b.png)

**Comment by GonzoKK** [comment]
Also looks like the field names are different

![image](https://user-images.githubusercontent.com/38913162/64375211-b628b800-d025-11e9-8c63-ac60c9442c77.png)
```
private ExchangeTicker ParseTicker(string marketSymbol, JToken data)
{
    return this.ParseTicker(data, marketSymbol, "sell_price", "buy_price", "buy_price", "average_price", "units_traded", "date", TimestampType.UnixMilliseconds);
}
```

{{
  "opening_price": "12625000",
  "closing_price": "12637000",
  "min_price": "12550000",
  "max_price": "12700000",
  "units_traded": "675.36",
  "acc_trade_value": "8520407176.87",
  "prev_closing_price": "12625000",
  "units_traded_24H": "16576.69",
  "acc_trade_value_24H": "209272210667.34",
  "fluctate_24H": "4,000",
  "fluctate_rate_24H": "0.03"
}}

**Comment by jjxtra** [comment]
Put in a sort of fix for this, this exchange seems to have some design issues...

**Comment by GonzoKK** [comment]
**Bithumb**
 ✓ GetTickersAsync: 93 items [0,471s]
 ✗ GetCurrenciesAsync: ERROR The method or operation is not implemented. [0,000s]
 ✓ GetMarketSymbolsAsync: 93 items [0,534s]
 ✗ GetMarketSymbolsMetadataAsync: ERROR The method or operation is not implemented. [0,000s]

![image](https://user-images.githubusercontent.com/38913162/64407924-d5efc880-d085-11e9-9c45-e8685ab382da.png)
