### ISSUE TITLE
Coinbase GetTickersAsync Problem in DEBUG mode (ClientWebSocket.cs)

### ISSUE THREAD

**Issue by GonzoKK** [jjxtra/ExchangeSharp#437]
**Coinbase** > **GetTickersAsync**.

Works in Build, but not in Debug. Gives Error with **ReadTask()** in **ClientWebSocket**.cs

I'm struggling with this one. Not sure why its happening. Can someone else also please test?

![image](https://user-images.githubusercontent.com/38913162/64471341-dc974200-d150-11e9-9c68-445ddf4a967e.png)

**Comment by jjxtra** [comment]
VS 2017 I see the exception but not the impact. When a web socket is disposed, it's cancel token is triggered, causing any pending web socket operations using that cancel token to throw operation cancel exceptions, which causes the web socket threads to end. Maybe there is a tidier way to do this without exceptions I am not sure of one.

```
var api = new ExchangeCoinbaseAPI();
var t = api.GetTickersAsync().Sync();
Console.ReadLine();
```
