### ISSUE TITLE
Bittrex: long running websocket will eventually error

### ISSUE THREAD

**Issue by vslee** [jjxtra/ExchangeSharp#446]
This one is hard to reproduce, but on a long running TradesWebsocket, will hit this error. I'm thinking it's likely during certain reconnections. Although most of the time, reconnections do work. 

2019-09-02 18:34:15.9144|INFO|ExchangeSharp.Logger|Error invoking hub proxy SubscribeToExchangeDeltas: System.InvalidOperationException: Connection was disconnected before invocation result was received.
   at ExchangeSharp.SignalrManager.SignalrSocketConnection.OpenAsync(String functionName, Func`2 callback, Int32 delayMilliseconds, Object[][] param)

**Comment by jjxtra** [comment]
The only odd-ball on signalr... why??? :) Not sure on this one though, I've been over this code a lot...

**Comment by vslee** [comment]
I think possibly it might be if the connection disconnects in the time after it connects but before the invocation is made?

**Comment by jjxtra** [comment]
I've made some tweaks in branch WebSocketAsync, can you try that branch and let me know if you see the issue?

**Comment by jjxtra** [comment]
I missed one line, make sure to get absolute latest of that branch :)

**Comment by vslee** [comment]
Looks like fairly wide reaching changes. I will probably have to run it for a little over a week to verify that it's fixed (since it's hard to reproduce on the spot). Not sure if you want to keep the branch hanging that long.

**Comment by jjxtra** [comment]
Keep it as long as needed to fix issue, can merge master in regularly.

**Comment by vslee** [comment]
Interesting thing about the new branch is that bc the socket isn't returned to the caller immediately, there's a delay before the rest of the properties (Connected, Disconnected, etc...) are able to be set. 

``` C#
			var exchangeAPI = new ExchangeBittrexAPI();
			Logger.Info("starting");
			using (var socket = await exchangeAPI.GetTradesWebSocket(async kvp =>
				{
					Console.WriteLine($"{kvp.Key}, {kvp.Value}");
				}, null))
			{
				socket.ConnectInterval = TimeSpan.FromSeconds(0);
				socket.Connected += async s =>
				{
					Logger.Debug("connected");
				};
				socket.Disconnected += async s => Logger.Debug("disconnected");
				Logger.Debug("finished setting socket properties");
				Console.WriteLine("Press ENTER to shutdown.");
				Console.ReadLine();
			}
```
![image](https://user-images.githubusercontent.com/366757/64662646-ff01b780-d3fd-11e9-9af2-a2ac435f533b.png)
From that picture, you can see that it calls create socket at 4 seconds. After that point, trades start coming in. However, the rest of the socket properties aren't able to be set until the 28 second mark. Thus, if the socket got disconnected during that time, then it anything in the Disconnected property wouldn't be able to respond to it.

**Comment by jjxtra** [comment]
I don't see the connect delay in the console example. There is about a 1.5 second delay to the connect event, of which 1 second is on purpose to allow the caller to set a connect event.

Trades sometimes take a few seconds, or sometimes come in almost right away. Where did you get 28 seconds from?
```
2019-09-10 20:39:47.2650|INFO|ExchangeSharp.Logger|ExchangeSharp console started.
2019-09-10 20:39:47.3446|INFO|ExchangeSharp.Logger|Connecting web socket...
Press any key to quit.
2019-09-10 20:39:49.0115|INFO|ExchangeSharp.Logger|Web socket connected
2019-09-10 20:39:50.4303|INFO|ExchangeSharp.Logger|USD-BTC: 2019-09-11T02:39:50,p:10060.00000000,a:0.00189221,Buy,id:39237108,
```

**Comment by jjxtra** [comment]
Looks like it did recover. I've tweaked the code slightly to log an info message in the case where it disconnects while performing the invoke, in which case you won't see the error anymore unless you are at info log level. I've been running for a couple days now with the code before this change and have not yet seen the error.

**Comment by vslee** [comment]
Sounds like a good solution. My internet has been a bit unstable (I have been messing with my router) so that's probably why I'm able to elicit the error more often.
