### ISSUE TITLE
C# 8.0 / .NET CORE 3

### ISSUE THREAD

**Issue by jjxtra** [jjxtra/ExchangeSharp#450]
The csharp8 branch contains all c# 8 work including nullable reference types, pattern matching, async enumerable and other syntax shortcuts. Resolve this issue upon merge to master with no warnings.

**Comment by vslee** [comment]
I took a look at the first commit. When I try running it, upon the instantiation of the exchangeAPI, it throws: `System.NotSupportedException: 'The requested security protocol is not supported.'`

**Comment by vslee** [comment]
nevermind, looks like it may be something on my end

**Comment by jjxtra** [comment]
Nice, get rid of ssl 3 looks like a good idea to me.

**Comment by vslee** [comment]
We might want to merge the changes so far into the master branch before this branch gets stale. Otherwise, would probably have conflicts in the future.

**Comment by jjxtra** [comment]
I may end up deleting the branch. There’s a lot to do to really get on csharp 8 and I just don’t have the time to do it.

**Comment by vslee** [comment]
I haven't looked much into C# 8, but my understanding is that its features can be introduced gradually rather than having to do the entire project at once.

**Comment by jjxtra** [comment]
True. Probably the nullable reference type makes sense that way. Maybe the asynchronous iterator stuff would be a good first candidate.
