### ISSUE TITLE
Bitfinex: GetOrderBook always results in "error",10020,"symbol: invalid"

### ISSUE THREAD

**Issue by amirderakh** [jjxtra/ExchangeSharp#460]
Hi,
I can't manage to load Bitfinex orderbooks.

GetOrderBookAsync("btcusd") and interestingly
GetOrderBooksAsync()

both result in "error",10020,"symbol: invalid".

I use v0.6.2 compiled for x64 on Win10.
Other exchanges return the order book like expected.

Am I doing sth wrong, is it the exchange's fault or is something missing in ExchangeSharp?
Thanks

**Comment by jjxtra** [comment]
Fixed in latest master, I guess they are on uppercase symbols now for v2 api...
