### ISSUE TITLE
Consider to make the console app more friendly and standard

### ISSUE THREAD

**Issue by johnnyasantoss** [jjxtra/ExchangeSharp#464]
I'm currently using ExchangeSharp and I find quite troublesome to use this console app. The code also look like if it grew without much design being applied to the final api.

I would suggest to use something like [Commandline][1] package to handle the CLI parsing and then build the commands in a more standardized way.

At the time I'm writing this issue I have already started working in a proposal which you can check at [my fork][2].

 [1]: https://github.com/commandlineparser/commandline
 [2]: https://github.com/BitonicNL/ExchangeSharp/tree/console

**Comment by jjxtra** [comment]
Feel free to open pr and we can have a look. Command line project is meant for examples not military grade production.

**Comment by johnnyasantoss** [comment]
Okay :) As soon as I migrate all the current commands I'll create a PR :stuck_out_tongue:
