### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by johnnyasantoss** [jjxtra/ExchangeSharp#466]
Hey :wave:!

I noticed that in the contributing guide it suggests to use tabs the default form of indentation, but most of the files in this project use 4 spaces, or they have spaces and tabs mixed (which is a mess, IMO).

What should I be using on my next PRs?

I personally would recommend using spaces are they are a more reliable way to show empty space (they don't change from editor/IDE) and also use [`.editorconfig`](https://editorconfig.org/) which is supported by basically all C# IDEs/Editors (e.g. Rider, VS, VSCode) and would make the chosen standard auto-enforced :)

**Comment by vslee** [comment]
I prefer tabs since untabbing/aligning is easier, but I'll leave it up to jjxtra. There is an .editorconfig already (from your PR #461) but I don't think it retroactively modifies all of the old files to comply.

**Comment by jjxtra** [comment]
I've always preferred tabs as well. VS does 4 spaces by default I think, so I don't think it is critical that we mandate one way or the other. You can always type the last brace of a file to auto-format the file.
