### ISSUE TITLE
Target netcoreapp2.0

### ISSUE THREAD

**Issue by johnnyasantoss** [jjxtra/ExchangeSharp#477]
As discussed in https://github.com/jjxtra/ExchangeSharp/pull/475#discussion_r342729770 we could start using `netstandard20` as a base runtime for this package and _maybe_ drop the overlapping support for `net472`.

**Comment by vslee** [comment]
Yes, we can change to targeting  `netstandard20` only. This would simplify the project, will still retaining compatibility with .net framework 4.6.1+ and .net core 2.0+. Go ahead and send a PR when you're ready and we can merge it in.
