### ISSUE TITLE
Improve proxy settings

### ISSUE THREAD

**Issue by johnnyasantoss** [jjxtra/ExchangeSharp#483]
Improve this piece of code to be more flexible and accessible in C# not only by env vars.

Maybe a singleton called `ExchangeSharpGlobalSettings`?

https://github.com/jjxtra/ExchangeSharp/blob/d9e921d3f566e5336fdcc65f698df2a463f10d16/ExchangeSharp/API/Common/APIRequestMaker.cs#L34-L44

**Comment by jjxtra** [comment]
Exposed on APIRequestMaker on latest master

**Comment by johnnyasantoss** [comment]
@jjxtra Thanks! I was creating some issues to remember fixing this in the future but, you already fixed it. :stuck_out_tongue:
