### ISSUE TITLE
HitBTC OnGetDepositHistoryAsync NOT "returning everything"

### ISSUE THREAD

**Issue by GonzoKK** [jjxtra/ExchangeSharp#484]
small tweak required

![image](https://user-images.githubusercontent.com/38913162/68660812-8e346400-0542-11ea-8c86-420336095afb.png)

**Comment by jjxtra** [comment]
Are you able to pr this?

**Comment by GonzoKK** [comment]
Never done a pr before :/

I get stuck here...

![image](https://user-images.githubusercontent.com/38913162/68736710-1457b580-05ea-11ea-9791-8b7a05cdd767.png)

**Comment by GonzoKK** [comment]
reopened...

**Comment by jjxtra** [comment]
Github UI is not the greatest, but there is a "compare across forks" link in blue, click that.
