### ISSUE TITLE
Should I add pre-compiled binaries to tag v0.6.3?

### ISSUE THREAD

**Issue by johnnyasantoss** [jjxtra/ExchangeSharp#495]
I was on uploading the zip files to the latest release (to make the installation script _actually_ work) when I thought that it could be seemed as a weird behavior to add these binaries if the commit that makes this possible is not in this tag.

I would have added this note to make explicit that it was edited.
*Note: these pre-compiled binaries were built from a [patched version](https://github.com/johnnyasantoss/ExchangeSharp/releases/tag/v0.6.3-patched) of this tag with [this commit](https://github.com/jjxtra/ExchangeSharp/commit/447d7348fcc0062535025f4135eec8f10d7a9952).* \
*You can verify the integrity of these builds by checking the commit tree from that repo or you can build it yourself follow [this guide](https://github.com/jjxtra/ExchangeSharp/blob/master/BUILDING.md).*

What do you guys think? @vslee @jjxtra

**Comment by vslee** [comment]
I don't think it's really necessary since our next release should be coming out in less than 10 days. That release will be triggered by your new pipeline and upload the binaries.

**Comment by johnnyasantoss** [comment]
Okay, let's wait then :)

**Comment by vslee** [comment]
New month started today. Do we have to do anything to push the new release or will the pipeline take care of it?

**Comment by johnnyasantoss** [comment]
> New month started today. Do we have to do anything to push the new release or will the pipeline take care of it?

It should be automatically :thinking: but if you push a new tag it will be taken care of.
Maybe there's something wrong with the cron on the scheduled job.
