### ISSUE TITLE
ExchangeSharp Windows Form

### ISSUE THREAD

**Issue by quangtho2910** [jjxtra/ExchangeSharp#50]
How can i run ExchangeSharp windows form @jjxtra? I can run the console sample app but i can't run the windows form example.

**Comment by jjxtra** [comment]
If you create a Windows forms application and link the library it *should* build the Windows Forms version of it, allowing you access to the forms. .NET core will not allow this. You have to have a Windows classis console or forms application.

**Comment by quangtho2910** [comment]
"Link the library": you mean create windows form project and add dll file to dependencies or using nuget right?

**Comment by jjxtra** [comment]
Correct

-- Jeff

**Comment by quangtho2910** [comment]
Hi @jjxtra 

Already create new windows form project, add nuget reference, replace default form with both PlotForm.cs and PlotForm.Designer.cs code. But when i ran the windows form, only the blank form appeared.
