### ISSUE TITLE
Making Sense of Base/Quote Currency Ordering for Symbol Strings

### ISSUE THREAD

**Issue by nh43de** [jjxtra/ExchangeSharp#500]
Ok, 

So typically a currency pair is expressed as BASE-QUOTE (note ordering)

E.g. 
- EUR-USD is 1.2
- XLM-BTC is 0.0000077

Some exchanges list these reverse, e.g. Bittrex. For these exchanges that list the symbols in reverse, there is a property called MarketSymbolIsReversed which will translate symbols for the exchange properly. However, it does not function as designed.

When translating between global market symbols <->exchange symbols, there is some unexpected behavior based on our assumptions above. See the following evaluations (this is using the Bittrex API where MarketSymbolIsReversed = true):

![image](https://user-images.githubusercontent.com/7240342/69924652-1dfa6d80-1472-11ea-9f64-6ca36efbd31c.png)

1) gms (global market symbol) above should be "XLM-BTC" because Bittrex symbols are reversed, and XLM is the base currency, so using global standards of BASE-QUOTE, it should be "XLM-BTC" but it does not evaluate as such

![image](https://user-images.githubusercontent.com/7240342/69924954-7ed67580-1473-11ea-8784-15af1d0b55b5.png)

2) ems (exchange market symbol) should be "BTC-XLM" because again, using global standards of BASE-QUOTE, and Bittrex is reversed, converting "XLM-BTC" global ticker to market ticker should evaluate to "BTC-XLM", which is the Bittrex market ticker
3) ems2 is correctly evaluated to the exchange market symbol for Bittrex composed using the base/quote currency strings as separate inputs
4) gms2, which is the global market symbol of the "BTC-XLM" market on the Bittrex exchange  should be "XLM-BTC", again because XLM is the base currency

The comments in the code are confusing/ambiguous at best and contradictory at worst:

![image](https://user-images.githubusercontent.com/7240342/69924709-66199000-1472-11ea-80c1-7555695b7e4d.png)

Can someone shed some light on this?

![image](https://user-images.githubusercontent.com/7240342/69931597-7c811500-148d-11ea-8630-9ee241ea4a58.png)

**Comment by vslee** [comment]
I'll let @jjxtra comment, as he did most of the work on the global market symbols.

**Comment by jjxtra** [comment]
This is the beauty of open source. Feel free to submit a pr and we will have a look!

**Comment by nh43de** [comment]
@jjxtra  I want to make sure there's unit tests etc. for this and make sure the PR is well done.. it may take some time. Will circle back in the next 30-60 days.

**Comment by jjxtra** [comment]
Thanks for even being willing to share at all, no rush at all :)

**Comment by nh43de** [comment]
Created PR #515 

Thanks for this awesome project
