### ISSUE TITLE
Inconsistencies with GetRecentTradesAsync / GetHistoricalTradesAsync across Exchanges

### ISSUE THREAD

**Issue by GonzoKK** [jjxtra/ExchangeSharp#508]
I have just started to delve into this and will add comments/feedback as I go...

For consistency across exchanges - I would prefer GetRecentTradesAsync and/or GetHistoricalTradesAsync to accept a numerical limit (eg 100) on number of Trades.  It currently varies wildly, for example...

**Binance**
 ✓ GetRecentTradesAsync: (ETHBTC) 4984 items [3,972s]
 ✓ GetHistoricalTradesAsync: (ETHBTC) 4978 items [1,632s]
**Bittrex**
 ✓ GetRecentTradesAsync: (BTC-RVN) 100 items [0,351s]
 ✓ GetHistoricalTradesAsync: (BTC-RVN) 14400 items [2,190s]
**HitBTC**
 ✓ GetRecentTradesAsync: (BCNBTC) 10 items [0,009s]
 ✓ GetHistoricalTradesAsync: (BCNBTC) 100 items [0,300s]

**Comment by GonzoKK** [comment]
Problem 01: On Bittrex, OnGetHistoricalTradesAsync uses GetTicks as a hack, HOWEVER it hardcodes every trade to be a BUY. IMO this can be very confusing as it applies there are no SELLS!

![image](https://user-images.githubusercontent.com/38913162/72663974-3530f280-3a01-11ea-87c7-a038f64fb3cf.png)

![image](https://user-images.githubusercontent.com/38913162/72663986-40841e00-3a01-11ea-8d24-9afe341fc589.png)

**Comment by vslee** [comment]
Looks like there's a new V[3 endpoint that provides the trades directly](https://bittrex.github.io/api/v3#operation--markets--marketSymbol--trades-get) instead of being a hack. If you want to update the code here, I can incorporate it.

**Comment by GonzoKK** [comment]
That v3 endpoint provides the same results as the current GetRecentTradesAsync which uses https://bittrex.github.io/api/v1-1#operation--public-getmarkethistory-get

They both return the same 100 records (some field names have changed). But in essence that functionality already exists in Sharp. 

v1.1 https://api.bittrex.com/api/v1.1/public/getmarkethistory?market=BTC-DOGE

v3 https://api.bittrex.com/v3/markets/DOGE-BTC/trades

![image](https://user-images.githubusercontent.com/38913162/72669746-519f5000-3a3e-11ea-8fd4-1b68ea67e4cf.png)

**Comment by vslee** [comment]
I see. Do you have any suggestions for OnGetHistoricalTradesAsync()?

**Comment by GonzoKK** [comment]
For Bittrex - I'm not aware of an endpoint that allows you to query trades by dates. And I don't think panelbeating Candle data is "correct". Candles are not trades.

So in the case of Bittrex v3 - I'd say **OnGetHistoricalTradesAsync** is **unsupported.**

**Comment by GonzoKK** [comment]
Problem 02 - Many exchanges support specifying a **limit** for number of trades.  Currently however - neither GetHistoricalTradesAsync/GetRecentTradesAsync accept **int? limit = null** as an argument.

As a result, in Sharp - limit is hard coded on many exchanges. Bitfinex is just one example... 
 ![image](https://user-images.githubusercontent.com/38913162/72712051-f753db80-3b72-11ea-85a8-b11d3751be56.png)
Bitfinex however supports a limit of **10000** https://docs.bitfinex.com/reference#rest-public-trades

On my side: 

1. I've added int? limit as a parameter to GetHistoricalTradesAsync & GetRecentTradesAsync (this impacts many files)
2. At the moment I'm busy adding/fixing GetRecentTradesAsync on a few exchanges (Binance, HitBTC, Bitfinex and some others)
![image](https://user-images.githubusercontent.com/38913162/72716270-99c38d00-3b7a-11ea-9a98-ebde461d249d.png)
3. For GetRecentTradesAsync , the sort order will be Descending (ie newest trades first)

Within 24 hours - I'll drop a link here to a zip file with updated source files

**Comment by GonzoKK** [comment]
Since I cant reopen this issue - I've created a new ticket at https://github.com/jjxtra/ExchangeSharp/issues/510
