### ISSUE TITLE
Is there plans to implement GetOrderDetails for Poloinex?

### ISSUE THREAD

**Issue by einewton** [jjxtra/ExchangeSharp#51]
I have a FEATURE REQUEST

Details:
When I make an order, and I want to get the details of that order to Poloniex I get a not implemented exception and was hoping to know if this is something that'll be added?

Thanks so much for this project, I just started to play with it and you have done exceptional work.

**Comment by jjxtra** [comment]
No plans currently, but you are welcome to implement the function if you like :)

**Comment by bichuga** [comment]
This is complete. https://github.com/jjxtra/ExchangeSharp/pull/67

**Comment by einewton** [comment]
Thanks so much bichuga!!! Huge help here!
