### ISSUE TITLE
How to get Price change percent from ticker 

### ISSUE THREAD

**Issue by fazeelmehar** [jjxtra/ExchangeSharp#520]
There is problem to get **Price Change Percent** from ticker because the limited variable set in 
ExchangeSharp.ExchangeTicker class. So how we get  **Price Change Percent** from ticker

```
public sealed class ExchangeTicker
    {
        public ExchangeTicker();
        public string Id { get; set; }
        public string MarketSymbol { get; set; }
        public decimal Bid { get; set; }
        public decimal Ask { get; set; }
        public decimal Last { get; set; }
        public ExchangeVolume Volume { get; set; }

        public void FromBinary(BinaryReader reader);
        public void ToBinary(BinaryWriter writer);
        public override string ToString();
    }
```

**Comment by vslee** [comment]
Adding **Price Change Percent** to `ExchangeTicker` would be a somewhat large undertaking because the code for all of the different exchanges would need to be updated. If you are willing to try, send a pull request and we'll merge it.

**Comment by GonzoKK** [comment]
Alternatively, use **GetCandlesAsync** to get any price history using candle data.

**Comment by fazeelmehar** [comment]
> Alternatively, use **GetCandlesAsync** to get any price history using candle data.

I am already using it                 var Candles = await ExchangeApi.GetCandlesAsync(PairName, 86400, DateTime.UtcNow.AddMonths(-1), DateTime.UtcNow);

**Comment by fazeelmehar** [comment]
> > Alternatively, use **GetCandlesAsync** to get any price history using candle data.
> 
> I am already using it var Candles = await ExchangeApi.GetCandlesAsync(PairName, 86400, DateTime.UtcNow.AddMonths(-1), DateTime.UtcNow);

**Comment by fazeelmehar** [comment]
I am already using it 
`**var Candles = await ExchangeApi.GetCandlesAsync(PairName, 86400, DateTime.UtcNow.AddMonths(-1), DateTime.UtcNow);**`
But we need a socket connection to get auto updates Tickers

**Comment by fazeelmehar** [comment]
Alternatively, I use **Binance.Net** Library for Tickers
```
 using (var client = new Binance.Net.BinanceSocketClient())
            {
                var successSymbol = client.SubscribeToSymbolTickerUpdatesAsync("btcusdt", (data) =>
                {
                }
            }
```

**Comment by fazeelmehar** [comment]
> Adding **Price Change Percent** to `ExchangeTicker` would be a somewhat large undertaking because the code for all of the different exchanges would need to be updated. If you are willing to try, send a pull request and we'll merge it.

Sure. In future

**Comment by GonzoKK** [comment]
Out of interest - which price change are you requiring - 24 hours, 1hour?

**Comment by fazeelmehar** [comment]
> Out of interest - which price change are you requiring - 24 hours, 1hour?

24 hour

**Comment by GonzoKK** [comment]
What I like about the **GetCandlesAsync** approach, you basically can get any time frame you want. Here's **BSVUSD** at one hour intervals. I have it on a timer that refreshes every minute or every hour depending on the candle.

![image](https://user-images.githubusercontent.com/38913162/74350874-0bc87400-4dbf-11ea-878f-a73203f754d1.png)

**Comment by fazeelmehar** [comment]
> What I like about the **GetCandlesAsync** approach, you basically can get any time frame you want. Here's **BSVUSD** at one hour intervals. I have it on a timer that refreshes every minute or every hour depending on the candle.
> 
> ![image](https://user-images.githubusercontent.com/38913162/74356686-6c5baf00-4dc7-11ea-8925-c64c2a79463e.png)
> Edit: Percent calc fix

This approach is also good. Thank You @GonzoKK
