### ISSUE TITLE
WebSocket unable to reconnect after lost connectivity (handshake 400)

### ISSUE THREAD

**Issue by novecento** [jjxtra/ExchangeSharp#530]
Hi, I'm facing a strange behavior: I subscribe correctly to sockets, more than one, but when server lost internet connectivity, when it comes again socket doesn't able to reconnect automatically and code 
await webSocket.ConnectAsync(Uri, cancellationToken);
return 'The server returned status code '400' when status code '101' was expected".

Test case is simple because I simply detach and re-attach wifi during execution.

Am I the only one with this simple strange behavior?

Thanks.

**Comment by jjxtra** [comment]
Which exchange(s)?

**Comment by novecento** [comment]
BitMEX

**Comment by jjxtra** [comment]
Bitmex is the only exchange with reported web socket issues, I would suggest to contact them
