### ISSUE TITLE
problems upgrading from 0.3.5

### ISSUE THREAD

**Issue by paulc1983** [jjxtra/ExchangeSharp#539]
Hi I am trying to upgrade a project. ExchangeVolume.QuantityAmount no longer exists and I can't see what happened. I cloned the code but there is no source control history and I can't see any kind of documentation. Is there an old GitHub repo where I can see the history of the files or any kind of release documentation?

failing that can anyone tell me what quantity amount was changed to?

Thanks

Paul

**Comment by vslee** [comment]
You're probably looking for QuoteCurrencyVolume or BaseCurrencyVolume

**Comment by kacey90** [comment]
I have a similar state of confusion. In my own version, it was Exchange.ConvertedVolume that was used. Which of the two (QuoteCurrencyVolume or BaseCurrencyVolume) should replace that?
