### ISSUE TITLE
Do not use extra parameters, and in for loop override price field

### ISSUE THREAD

**Issue by gungoren** [jjxtra/ExchangeSharp#544]
https://github.com/jjxtra/ExchangeSharp/blob/292bef292e2ee07c1f45f89252aa1d2f98718a39/src/ExchangeSharp/API/Exchanges/Bitstamp/ExchangeBitstampAPI.cs#L211

**Comment by vslee** [comment]
I'm not sure what you're talking about. Can you send a pull request, or paste the updated method here?
