### ISSUE TITLE
bug periodInSeconds gives error for polonium exchange

### ISSUE THREAD

**Issue by erwin-beckers** [jjxtra/ExchangeSharp#55]
I have a BUG REPORT

Details:
following code gives an API exception "Please specify valid period" for the poloniexapi
Other api's like bittrex and binance work fine

```

var api = new ExchangePoloniexAPI();
var newCandles = api.GetCandles(" BTC_AMP", (60*60), DateTime.Now.AddMonths(-1));

```

**Comment by jjxtra** [comment]
Please read Poloniex API docs, your period is not supported.
