### ISSUE TITLE
ProcessHistoricalTrades wrong start/end timestamp when having period with 0 entries.

### ISSUE THREAD

**Issue by BZ-CO** [jjxtra/ExchangeSharp#554]
I've currently tested the behaviour only on Poloniex.

Exchange: Poloniex
Symbol: BNB_BTC Start: 1602663800 End 1602667400 | 10/14/2020 8:23:20 AM +00:00 - 10/14/2020 9:23:20 AM +00:00
Response: `[]`
Symbol: BNB_BTC Start: 1602663800 End 1602660200 | 10/14/2020 8:23:20 AM +00:00 - 10/14/2020 7:23:20 AM +00:00
Response: `[
  {
    "globalTradeID": 491988215,
    "tradeID": 3294,
    "date": "2020-10-14 07:47:26",
    "type": "buy",
    "rate": "369.52753040",
    "amount": "0.00030831",
    "total": "0.11392903",
    "orderNumber": 2651864817
  }
]`
Symbol: BNB_BTC Start: 1602658045 End 1602661645 | 10/14/2020 6:47:25 AM +00:00 - 10/14/2020 7:47:25 AM +00:00
Response: `[
  {
    "globalTradeID": 491983698,
    "tradeID": 3293,
    "date": "2020-10-14 06:55:18",
    "type": "buy",
    "rate": "370.75337811",
    "amount": "0.00032186",
    "total": "0.11933068",
    "orderNumber": 2651462220
  }
]`
Symbol: BNB_BTC Start: 1602654917 End 1602658517 | 10/14/2020 5:55:17 AM +00:00 - 10/14/2020 6:55:17 AM +00:00
Response: `[]`
Symbol: BNB_BTC Start: 1602654917 End 1602651317 | 10/14/2020 5:55:17 AM +00:00 - 10/14/2020 4:55:17 AM +00:00
Response: `[]`
Symbol: BNB_BTC Start: 1602654917 End 1602651317 | 10/14/2020 5:55:17 AM +00:00 - 10/14/2020 4:55:17 AM +00:00
Response: `[]`
Symbol: BNB_BTC Start: 1602654917 End 1602651317 | 10/14/2020 5:55:17 AM +00:00 - 10/14/2020 4:55:17 AM +00:00
Response: `[]`
Symbol: BNB_BTC Start: 1602654917 End 1602651317 | 10/14/2020 5:55:17 AM +00:00 - 10/14/2020 4:55:17 AM +00:00
Response: `[]`
Symbol: BNB_BTC Start: 1602654917 End 1602651317 | 10/14/2020 5:55:17 AM +00:00 - 10/14/2020 4:55:17 AM +00:00
Response: `[]`

**Comment by vslee** [comment]
Thanks for filing this bug. If you send a pull request with the solution, we'll be happy to merge it. If you don't know how, you can also post the updated code here.

**Comment by BZ-CO** [comment]
#555
