### ISSUE TITLE
Discord channel does not have any chats

### ISSUE THREAD

**Issue by BadgerTheAdger** [jjxtra/ExchangeSharp#557]
Hi guys, I wanted to join the discord channel to chat with you chaps regarding the library documentation. However the discord channel seems to not have any chats, that's what discord told me. 
![image](https://user-images.githubusercontent.com/33373431/99489723-0cef8880-2971-11eb-8f12-f71c5e2e9c47.png)

**Comment by vslee** [comment]
You have to click the DigitalRuby icon to the left of your screenshot
