### ISSUE TITLE
General project documentation / some wikis?

### ISSUE THREAD

**Issue by BadgerTheAdger** [jjxtra/ExchangeSharp#558]
Hi everyone, I'm working on preparing project wikis / documentation for my crew who are using the library, for instance they had questions on such things as global / exchange symbols, code structure, etc. - I know these are not hard to answer but it's just that it would be nice to have some wiki document to include all that. I'm preparing my own documentation which we could maybe integrate into the wiki I suppose?

**Comment by vslee** [comment]
Yes, feel free to put your docs in the wiki here

**Comment by jjxtra** [comment]
I've added you as a collaborater, feel free to go to town on the wiki :)
