### ISSUE TITLE
Inconsistent price documentation

### ISSUE THREAD

**Issue by borseno** [jjxtra/ExchangeSharp#566]
Hi guys,

I have my own documentation in a private fork which is different from the original Github's one **in some cases**. 

The case is price documentation:

>  BASE-QUOTE is read as 1 BASE is worth y QUOTE. 
     On 1/25/2020,
     - BTC-USD: $8,371; 1 BTC (base) is worth $8,371 USD (quote)
 
However, in fact, Binance & Coinbasepro etc. classes have the reversed concept: x base equals 1 quote.

For example, Binance's USDT-BTC price is 20000 

The private fork I'm working in just decided to change the documentation to match the binance's and coinbasepro's concepts.

However binance and coinbasepro concepts are different from ExchangeSharp. Looks like they are incorrect and the documentation is correct.

There are also exchanges such as BitPanda & Kraken that list base first and quote last (unlike Binance and Coinbasepro) which is the same concept as in ExchangeSharp, and their prices match the original documentation.

We can do either of the two:
1) Change the prices concept to match binance's one - I'll then easily upload the wikis that I have without modifying any contents
2) Fix binance&coinbaspro etc. exchanges (perhaps in the ExchangeAPI class and a flag indicating what prices are) - then I'll also need to upgrade wikis to get back to the original concept

Let me know what you think of this please

**Comment by vslee** [comment]
Closed by https://github.com/jjxtra/ExchangeSharp/commit/9cf6379dda9d97d9f0b9043946e7c371491c0893
