### ISSUE TITLE
Bittrex MarketSymbolIsReversed should be false

### ISSUE THREAD

**Issue by LucStr** [jjxtra/ExchangeSharp#578]
Hello I am using the Method IExchangeAPI.GlobalMarketSymbolToExchangeMarketSymbolAsync to get my GlobalMarketSymbol(BTC-ETH) to the ExchangeMarketSymbol (BTC-ETH). I saw, that BittrexAPI is setting the Property  MarketSymbolIsReversed to true, which results in the market symbol being (ETH-BTC). Therefore the websocket subscription doesn't work.

I was wondering why MarketSymbolIsReversed  is set to true, as the way I see it Bittrex is using the format BASE-QUOTE to describe it's markets.

Am I Interpreting something wrong?

best regards.

**Comment by vslee** [comment]
GlobalMarketSymbol has been a work in progress for a while, see:
https://github.com/jjxtra/ExchangeSharp/issues/570, https://github.com/jjxtra/ExchangeSharp/issues/566

There was a PR submitted to improve things, but it has stalled: https://github.com/jjxtra/ExchangeSharp/pull/565

If you'd like to submit your own PR, we'd be happy to merge it.
