### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by Diogovski** [jjxtra/ExchangeSharp#580]
Hi, i was wondering if am i able to use this code in a Windows Form Application(.NET Framework)?I am trying to build an application where the user can do everything he would do in the kucoin website/app! I am finding a hard time using the code.

**Comment by Diogovski** [comment]
???

**Comment by vslee** [comment]
This library works with .net framework and .net core apps, including Windows Forms. 
But unless you are comfortable sending pull requests back to us to fix any issues, I suggest you use a dedicated KuCoin library instead.
