### ISSUE TITLE
PlaceOrderAsync doesn't have a Funds option?

### ISSUE THREAD

**Issue by MoneyMachine555** [jjxtra/ExchangeSharp#582]
Hi, i am trying to write a function to buy a certain symbol, but i don't see the option of using funds, instead i only see the amount option? Is it possible to add he Funds option,pls?

**Comment by MoneyMachine555** [comment]
?

**Comment by MoneyMachine555** [comment]
???

**Comment by vslee** [comment]
Thanks for filing this feature request. If you send a pull request with the solution, we'll be happy to merge it. If you don't know how, you can also post the updated code here.

**Comment by vslee** [comment]
Okay, I'll close this for now. If you decide to try later, feel free to re-open.
