### ISSUE TITLE
Candles in websockets?

### ISSUE THREAD

**Issue by jdx-john** [jjxtra/ExchangeSharp#595]
I notice that Kraken's WS API provides `ohlc` but as far as I can see ExchangeSharp only exposes the REST version.
Is this a deliberate design or perhaps it's not seen as useful?
I wouldn't be surprised if there's already a utility class which will generate candles from the raw trades feed... I keep starting to write things then stumbling across existing implementations!

**Comment by vslee** [comment]
Streaming tickers is implemented in ExchangeSharp for many exchanges but not Kraken. If you'd like you submit an implementation as a Pull Request, we'd be happy to merge it!

**Comment by jdx-john** [comment]
@vslee I'm not referring to tickers, but to OHLC candles.

I thought that WS functionality for Kraken _is_ supported, e.g. `OnGetTickersWebSocketAsync` / `OnGetTradesWebSocketAsync` in `ExchangeKrakenAPI`?

But my question is that in `IExchangeAPI`, there is no signature defined at all for streaming OHLC data. Perhaps KRaken is the only exchange who added this (https://docs.kraken.com/websockets/#message-ohlc) or maybe everyone builds their own candles from raw trades data so it's not considered important?

So to submit a PR I would need to add a new API method on the interface and presumably dummy versions for every other exchange, as well as doing the implementation?

**Comment by vslee** [comment]
I see what you're saying, ExchangeSharp only had REST support for Candles, but not Websocket support. I just made a PR which adds Websocket support for candles. After my PR is merged, you can then add OHLC support to Kraken by overriding the `OnGetCandlesWebSocketAsync()` method in `ExchangeKrakenAPI.cs`.
