### ISSUE TITLE
Confused by Kraken XBT/XDG tickers 

### ISSUE THREAD

**Issue by jdx-john** [jjxtra/ExchangeSharp#599]
I know that for historical reasons Kraken uses these rather than BTC and DOGE, but I'm sure I've seen references to workarounds in the codebase? So I'm confused that I still have to use the Kraken-specific terms when working with `ExchangeKrakenAPI` - isn't the point any required translations should be done behind the scenes so exchanges can be used without special logic?

Or maybe I should be doing that step myself, is there an example?

**Comment by vslee** [comment]
There are `ExchangeMarketSymbolToGlobalMarketSymbolAsync()` and `GlobalMarketSymbolToExchangeMarketSymbolAsync()` that users can optionally tap into if they want. This is not done by default though.
