### ISSUE TITLE
HttpWebRequest is obsolete and its Timeouts is not implmented in netcore/net5.0

### ISSUE THREAD

**Issue by szmcdull** [jjxtra/ExchangeSharp#605]
I found that the RequestTimeout property is not working sometimes.
Today I wrote a simple Go program to test and verify it is not working.

```go
func hello(w http.ResponseWriter, req *http.Request) {
	fmt.Fprintf(w, `<body>`) // write something, flush and then sleep 10 secs
	w.(http.Flusher).Flush()
	time.Sleep(time.Second*10)
	fmt.Fprintf(w, `ok</body>`) // then write the remaining part
}

func main() {
	http.HandleFunc("/hello", hello)
	http.NewServeMux()
	http.ListenAndServe(":8090", nil)
}
```

In the client I specify a Timeout of 5 secs (while the server is using a delay of 10 secs). But it runs to the end successfully without raising any Exception.

Then I found this thread stating that the property is now a noop:
https://github.com/dotnet/runtime/issues/28404#issuecomment-453667038

I guess we should move on to the `System.Net.Http` package and classes like `HttpClient` + `HttpRequestMessage` etc.?

**Comment by vslee** [comment]
Good observation.

**Comment by vslee** [comment]
Moving to HttpClient would be nice, but would likely involve some effort. If you are interested in doing that, we would welcome your PR.

**Comment by szmcdull** [comment]
Indeed there would be much to change as there are many wrappers for request, response, headers etc. That's why I want to ask for consideration first. Don't if you have some requirement for code design/pattern?

**Comment by vslee** [comment]
You have submitted good patches in the past so we are familiar with your work. I am confident your code design for this will be good.

**Comment by szmcdull** [comment]
https://github.com/jjxtra/ExchangeSharp/pull/607
