### ISSUE TITLE
[Question] How to create multiple instances for an exchange? After all constructors become private

### ISSUE THREAD

**Issue by szmcdull** [jjxtra/ExchangeSharp#606]
Sometimes I need multiple instances of an exchange but with different credential. How to achieve that as all constructors become private?

**Comment by vslee** [comment]
Any thoughts @jjxtra?

**Comment by EmergentCybernetics** [comment]
We're interested in this feature as well.

**Comment by jjxtra** [comment]
Call GetExchangeAPI and cast as needed. No need for multiple instances it won't help performance.

**Comment by szmcdull** [comment]
There are some use cases. For example, we have a monitoring program to monitor multiple balance accounts under the same exchange.

**Comment by jjxtra** [comment]
You can use reflection to create the exchange. You'll have to call all the correct initialize as well. Architecturally it seems like we need a context as an optional last parameter to every call to provide credentials rather than making the ￼ creds members of the exchange class.￼

**Comment by jjxtra** [comment]
Another option would be to provide a static method that always creates a new exchange rather than reusing a cached version.￼

**Comment by jjxtra** [comment]
I'll go the static method unless anyone has any objections. Will do a commit later today.

**Comment by jjxtra** [comment]
Fixed in https://github.com/jjxtra/ExchangeSharp/pull/613, just call CreateExchangeAPI instead of GetExchangeAPI.
