### ISSUE TITLE
ExchangeBitrexapi Ticker always returning invalid market

### ISSUE THREAD

**Issue by vdboots** [jjxtra/ExchangeSharp#61]
I have a BUG REPORT

Details:

            var bitstampapi = new ExchangeBitstampAPI();
            var bitrextapi = new ExchangeBittrexAPI();
            var bitrextTicker = bitrextapi.GetTicker("btcusd"); // this always tells invalid market
            var bitstampticker = bitstampapi.GetTicker("XRPEUR");

Error Logs (if any):
ExchangeSharp.APIException: 'INVALID_MARKET'

**Comment by jjxtra** [comment]
Please check the symbols before posting an issue. btcusd is not supported on bittrex. Bitstamp separates pairs with a /.
