### ISSUE TITLE
Websocket threading implementation query?

### ISSUE THREAD

**Issue by jdx-john** [jjxtra/ExchangeSharp#623]
Just a quick question, is the ES architecture that each web-socket subscription is effectively running in its own thread? I know the code is heavily async/await based but what I'm wondering about is reentrancy. If I have callbacks set on 3 different web-sockets, can all be called at once, or are all updates placed on some internal queue? Or, could a single callback be called multiple times at once e.g. does my callback block the next message on this channel or is each message going to call into my callback even if it's already running?

**Comment by vslee** [comment]
I didn't write the internals, but from what I can gather, all updates are placed in an internal queue. The callbacks block the next message so they are executed sequentially. You can override that behavior in your own code if you'd like.

**Comment by jdx-john** [comment]
This would make sense. I might try examining the call-stack but I'm working on Mac and their version of Visual Studio leaves quite a lot to be desired.

**Comment by jjxtra** [comment]
Web socket is a serial queue for callbacks and sent messages
