### ISSUE TITLE
Is there a sample OrderBook implementation?

### ISSUE THREAD

**Issue by jdx-john** [jjxtra/ExchangeSharp#624]
I'm putting together a simple implementation that uses the `SortedDictionary` of Asks and Bids for Websockets (I guess it would work for REST too). I think this is consistent across all exchanges so I can contribute it but it seems like something that might already exist.
Kraken provides Checksum functionality to test your book hasn't gotten out of sync, not sure if others do this but ES doesn't currently expose this at all so I'd at least ad support in `ExchangeOrderBook`. Other than that it's basically just merging dictionaries.

**Comment by vslee** [comment]
Nothing outside of what is in this repo already. But if you do end up creating one, we'd be happy to merge it.

**Comment by jdx-john** [comment]
I was wondering if there was something lurking in the repo... I keep finding things! Very happy to share it if I can avoid making it specific to my application.
