### ISSUE TITLE
InitializeAsync is called with .Sync() which blocks the calling UI thread

### ISSUE THREAD

**Issue by bezysoftware** [jjxtra/ExchangeSharp#666]
I just noticed that for Kraken calling `ExchangeAPI.GetExchangeAPI` blocks the entire UI thread and freezes the application. After some digging I think that's caused by this:

https://github.com/jjxtra/ExchangeSharp/blob/master/src/ExchangeSharp/API/Exchanges/_Base/ExchangeAPI.cs#L74 which looks like a ticking time bomb :) 
I think the api should change to be Async, which would allow to await the initialize method, instead of calling `.Sync()`.

**Comment by vslee** [comment]
Yes, I think that's a good idea. Go ahead an submit a PR to change it to async
