### ISSUE TITLE
Poloniex: How to prevent "Complete: Error" withdrawals

### ISSUE THREAD

**Issue by bichuga** [jjxtra/ExchangeSharp#68]
Details:
Through some luck I discovered a coin, ARDR, that requires both an address and a "message" field to deposit to Bittrex, but Poloniex only allows you to provide an address for the withdrawal. 

![image](https://user-images.githubusercontent.com/9372553/37569575-9e5bd3d6-2aa1-11e8-9481-9b020686fe06.png)

I decided to get $5 of ARDR and try to initiate the transfer with both fields via the API. The API accepted it and after processing for a few minutes, the withdrawal changed to status "Complete: Error"

![image](https://user-images.githubusercontent.com/9372553/37569419-2a331eee-2a9f-11e8-856e-852635c40163.png)

The coins never got transferred - no matching transaction ever showed up on the blockchain. However the coins also never got credited back to my account. On reddit, it looks like this is a [pretty common problem](https://www.reddit.com/r/poloniex/search?q=complete%3A+error&restrict_sr=on&include_over_18=on&sort=relevance&t=all) when people mess up their withdrawal request. Support tickets to poloniex for this type of thing seem to take months to resolve.

The question is, how do we prevent someone from initiating a withdrawal like this and jamming up their coins? As far as I can tell, their [API](https://poloniex.com/support/api/) provides no hint to prevent this.

**Comment by jjxtra** [comment]
No easy way except throw an exception for that coin in the API

**Comment by bichuga** [comment]
But how to discover the coins to throw the exception about? I'm willing to implement something if we can come up with an idea.

**Comment by bichuga** [comment]
Would you be ok with a solution where I hardcode this mapping? If caller specifies incorrect number of fields throw?

**Comment by jjxtra** [comment]
Yes hard code is fine.

-- Jeff
