### ISSUE TITLE
Multi-user environment

### ISSUE THREAD

**Issue by Plumbly** [jjxtra/ExchangeSharp#682]
Hey All,

I am currently using ExchangeSharp in an environment where multiple users would be performing trades via the library and, because of how the library stores keys within the exchange instance, I will need to alter how it retrieves/uses keys for a request. Otherwise I anticipate that there is a risk of user's keys getting mixed up when requests are made, which is obviously less than ideal!

I intended to make these changes in a separate repo, but then it crossed my mind that it might be a nice contribution towards the project that would make using it more flexible. So just wanted to ask whether there was any desire to have this sort of functionality? Or is the intent to only ever have it work for a single user via the console app? 

Plumbly

**Comment by vslee** [comment]
I think we'd be interested in this. Can you propose your changes briefly here so we can review them before you spend too much time on them?

**Comment by Plumbly** [comment]
Hmm I probably need think about this a bit more, and have a deeper dive in the library code, but my first instinct is that the library shouldn't be managing the keys and maybe a simple solution is to require the consumer to have to pass the keys as parameters to any request that actually requires them. This could likely be introduced with little interference as well, since we could simply provide them as overloads to the existing methods. The legacy signatures could then be deprecated and a period of time be given for people to transition over, or simply left if you want to give people the choice.

Another possible option, would be to return a deep copy of the cached exchange instance when calling GetExchange? This would preserve any cached information, whilst preventing keys from being shared. However, whilst this would be relatively quick to implement, something feels quite hacky about it and I am not sure how performant this would be.

Just my initial thoughts to kickstart the discussion, but I will continue to have a think about better ways this can be done. It  would be great to here any thoughts/ideas any of you have as well.

**Comment by vslee** [comment]
How about having fluent composition, like:
```csharp
await exchangeAPI.WithKeys(...).PlaceOrderAsync(...);
```
That way, we don't have to change every method signature. And single users can still create an exchangeAPI with the keys stored, so that they don't have to deal with storing them and passing them every time?

**Comment by BZ-CO** [comment]
Another thing that should be considered is the rate limiter. Some exchanges charge requests per ip, other per key.
I think that it will be good if cache data is shared per all instances of the same exchange.

**Comment by jjxtra** [comment]
Working on rate limiter being static, stand-by...

**Comment by jjxtra** [comment]
Resolved in https://github.com/jjxtra/ExchangeSharp/pull/702

**Comment by jjxtra** [comment]
Is in master now.
