### ISSUE TITLE
Exchange name and ExchangeAPI access

### ISSUE THREAD

**Issue by jdx-john** [jjxtra/ExchangeSharp#689]
I feel like I'm missing something a bit obvious since I've been using ES for a while now, but working on a cross-exchange application I am using `var api = GetExchangeAPIAsync(name)`:

1. I wonder why this returns `IExchangeAPI` rather than `ExchangeAPI` and if casting is the only option? There's some useful symbol conversion utilities in `ExchangeAPI`.
2. When you have an `IExchangeAPI`, how can you ask it its name? I can't find a way which seems odd considering we even have `ExchangeName` helper and every exchange does list its name e.g. bottom of ExchangeKrakenAPI.cs

On 1. I am wondering if those helper methods would be better pulled into a utility class, maybe even as extension methods?

**Comment by vslee** [comment]
1. Can you specify what symbol conversion utilities you're talking about?
Also, can you do a quick mockup or describe what changing to a utility class or extension methods would look like?
2. I suppose you'd use reflection or `GetType()` to get the type name. @jjxtra, do you know of an easier way?

**Comment by jjxtra** [comment]
Should be a name property. If it's not on the interface we can add it.￼

**Comment by vslee** [comment]
It's a little more complicated in that, since there is not a `Name` property, but rather an `ExchangeName` partial class. See below:

https://github.com/jjxtra/ExchangeSharp/blob/c24ed064846e64ba335302549d6cba5e47e230e4/src/ExchangeSharp/API/Exchanges/Kraken/ExchangeKrakenAPI.cs#L1209

We may need to add a method in `ExchangeName` which takes an `ExchangeAPI` and returns the name as a string.

**Comment by jjxtra** [comment]
That's not a bad idea, we could also assign a Name property in the factory constructor of the exchange using said helper method.

**Comment by jjxtra** [comment]
Just looking at the code, looks like Name on the Exchange is being set and is available via the IName interface...

**Comment by vslee** [comment]
Okay I see that now. Does that work for you @jdx-john?

**Comment by jdx-john** [comment]
We still have the issue that `INamed` is implemented in `BaseAPI` which is a subclass of `ExchangeAPI`... but the `GetExchangeAPI` method returns `IExchangeAPI`. An API that requires you to cast the result isn't ideal so I'm wondering why we don't just return `ExchangeAPI`?

@vslee  
>Can you specify what symbol conversion utilities you're talking about?

We have a few methods like `ExchangeCurrencyToGlobalCurrencyAsync` and related. The inconsistency is actually just that this isn't on the interface, whereas `ExchangeMarketSymbolToGlobalMarketSymbolAsync` _is_. Maybe adding the declarations to `IExchangeAPI` would be easier. I spent a while getting annoyed I could convert a market name but not a currency, before finally realising the method exists the whole time but isn't on the interface!

**Comment by jjxtra** [comment]
We can add Inamed to the Iexchange API interface.￼

**Comment by jdx-john** [comment]
> We can add Inamed to the Iexchange API interface.￼

that would work neatly.

**Comment by jjxtra** [comment]
Ok, I looked at IExchangeAPI now, it inherits IBaseAPI which inherits INamed. So there should be a name property available on IExchangeAPI, is there not?

**Comment by bezysoftware** [comment]
Yes there is, I can see it

**Comment by vslee** [comment]
Great
