### ISSUE TITLE
Trying to get started but I cannot enter API keys

### ISSUE THREAD

**Issue by clemenslinders** [jjxtra/ExchangeSharp#693]
Hi,

I am trying to build a Poloniex trade bot.

For placing an order I had the following in mind:

        private static async Task<ExchangePoloniexAPI> CreatePoloniexAPI(string response = null)
        {
            var api = (await ExchangeAPI.GetExchangeAPIAsync(ExchangeName.Poloniex) as ExchangePoloniexAPI);
            return api;
        }

        private async void placeOrderButton_Click(object sender, EventArgs e)
        {
            var polo = await CreatePoloniexAPI();
            var orderRequest = new ExchangeOrderRequest
            {
                MarketSymbol = "FOO_FOO",
                Amount = 338.8732m,
                Price = 0.00000173m,
                IsBuy = true
            };

            polo.PrivateApiKey = new System.Security.SecureString();
            polo.PublicApiKey = new System.Security.SecureString();
            polo.PlaceOrderAsync(orderRequest).Wait();
        }

Whatever I try I cannot set the PrivateApiKey to for instance 1234 nor can I set the PublicApiKey to for instance ABCDE.

How would I do this?
And is this the way (In winforms) to place an order?

Kind regards,

Clemens Linders

**Comment by vslee** [comment]
Use `IExchangeAPI.LoadAPIKeysUnsecure()` instead

**Comment by clemenslinders** [comment]
Hi vslee,

Thanks for your reply.

So this would be the way to go:
    private static async Task<ExchangePoloniexAPI> CreatePoloniexAPI(string response = null)
    {
        var api = (await ExchangeAPI.GetExchangeAPIAsync(ExchangeName.Poloniex) as ExchangePoloniexAPI);
	api.LoadAPIKeysUnsecure("publicKey", "privateKey");
        return api;
    }




    private async void placeOrderButton_Click(object sender, EventArgs e)
    {
        var polo = await CreatePoloniexAPI();
        var orderRequest = new ExchangeOrderRequest
        {
            MarketSymbol = "FOO_FOO",
            Amount = 338.8732m,
            Price = 0.00000173m,
            IsBuy = true
        };

        polo.PlaceOrderAsync(orderRequest).Wait();
    }

**Comment by vslee** [comment]
Try it out and see if it works
