### ISSUE TITLE
Unable to LoadAPIKeys in Linux Docker container after restart: CryptographicException: Invalid data

### ISSUE THREAD

**Issue by bezysoftware** [jjxtra/ExchangeSharp#696]
I have an app running inside a linux docker container. Using `CryptoUtility.SaveUnprotectedStringsToFile` I save my strings to file, after which I create an exchange object and `LoadAPIKeys` I just created. This works.
After program finishes and I start it again I skip saving the strings, since they already exist, and I only want to `LoadAPIKeys` from the existing file. This fails with error 
```
Unhandled exception. System.Security.Cryptography.CryptographicException: Invalid data.
   at ExchangeSharp.DataProtector.ManagedProtection.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at ExchangeSharp.CryptoUtility.LoadProtectedStringsFromFile(String path)
   at ExchangeSharp.BaseAPI.LoadAPIKeys(String encryptedFile)
   at Program.<Main>$(String[] args) in /src/WebApplicatio
[WebApplication5.zip](https://github.com/jjxtra/ExchangeSharp/files/7683782/WebApplication5.zip)
n5/Program.cs:line 16
   at Program.<Main>(String[] args)
```

Reproducible sample attached [WebApplication5.zip](https://github.com/jjxtra/ExchangeSharp/files/7683809/WebApplication5.zip). After extract in shell call:
```
cd WebApplication5\WebApplication5
docker build -t test .
docker run -v ~/:/app/data test:latest
docker run -v ~/:/app/data test:latest # second time fails
```

First time you run it the files get created
Second time `LoadAPIKeys` fails

**Comment by bezysoftware** [comment]
I think I found the issue: the code on Linux lands in `public static RSA RSAFromFile(DataProtectionScope scope)` method which does this: 
`string xmlFile = (scope == DataProtectionScope.CurrentUser ? Path.Combine(System.Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "esku_123_abc.bin") :
`
It saves the file to `MyDocuments` folder, which in Docker container ends up in `/root/esku_123_abc.bin` which I wasn't mounting meaning that file doesn't survive container restart.
Solution it to mount that folder as well:
`docker run -v ~/:/app/data -v ~/:/root test:latest`

**Comment by vslee** [comment]
So you figured it out?

**Comment by bezysoftware** [comment]
Yes, found a solution. But perpahps the cryptographic details could be documented in readme somewhere

**Comment by vslee** [comment]
Good idea. If you have an idea of how to word it, send a PR and we'll be happy to add it.
