### ISSUE TITLE
Bitfinex don't submit order to tickers with special character ':'

### ISSUE THREAD

**Issue by MatheusKlauck** [jjxtra/ExchangeSharp#699]
I've tried to submit an order to market "DOGE:USD" at bitfinex, but the response was `APIException: {"message":"Unknown symbol"}`. But at the Bitfinex's platform, the name is right ("DOGE**:**USD").

**Comment by vslee** [comment]
Thanks for filing this bug. If you send a pull request with the solution, we'll be happy to merge it. If you don't know how, you can also post the updated code here.
