### ISSUE TITLE
Bittrex.Net 1.4.1 is the latest version that doesn't cause error. 2.0.8 is latest stable ver.

### ISSUE THREAD

**Issue by islandTraderFX** [jjxtra/ExchangeSharp#70]
I have a [BUG REPORT] or [FEATURE REQUEST]
Bittrex.Net  2.0.8 is latest stable version, but 1.4.1 is the latest version that works with ExchangeBittrexAPI.

Dunno if this is an issue, or is fine as is, just passing this along.  

Does not cause any issue unless update to latest stable Bittrex.Net is attempted in NuGet PM.

Details:

Error Logs (if any):
Severity	Code	Description	Project	Path	File	Line	Source	Suppression State	Tool
Error	CS0029	Cannot implicitly convert type 'CryptoExchange.Net.CallResult<int>' to 'Bittrex.Net.Objects.BittrexApiResult<int>'	ExchangeSharp(netstandard2.0)	C:\Users\DJH\Documents\Visual Studio 2017\Projects\Quantum Trader\packages\ExchangeSharp-master\ExchangeSharp\API\Exchanges	C:\Users\DJH\Documents\Visual Studio 2017\Projects\Quantum Trader\packages\ExchangeSharp-master\ExchangeSharp\API\Exchanges\ExchangeBittrexAPI.cs	213	Build	N/A	Compiler

Causes a conversion issue interacting with CryptoExchange.Net.CallResult<int>

ExchangeBittrexAPI.cs:

Line # 213:  BittrexApiResult<int> result = SocketClient.SubscribeToAllMarketDeltaStream

Thanks, as always.  Strong work!

**Comment by bichuga** [comment]
update your bittrex.net nuget package in your project

**Comment by jjxtra** [comment]
Fixed in latest commit and sent a new nuget package
