### ISSUE TITLE
ExchangeOrderRequest.Price is this the grand total price or price for one coin

### ISSUE THREAD

**Issue by clemenslinders** [jjxtra/ExchangeSharp#711]
Hi,

I am trying to built my BOT using ExchangeSharp in C#.

I have the class ExchangeSharp with the property Price.

Suppose the BTC is 43000 USDT and I want to buy 0.01 BTC.

Do I set the value of Price to 43000 or 0.01??

Thanks in advance.

Kind regards,

Clemens Linders

**Comment by jjxtra** [comment]
The price is what you pay for unit. So if you are buying Bitcoin with usd then you'll specific the price in usd. The amount you'll specify in Bitcoin.

**Comment by clemenslinders** [comment]
Hi Jeff,

Thanks for your reply.
I expected this to be the answer, but I wanted to be sure.

Should others in the future read this post, than perhaps it is important that I rectify an error in my question.

The question was Do I set the price to 43000 or 0.01. This should have been: Do I set the price to 43000 or 430 (0.01 x 43000).

But as you said the price is the unit price, so it is 43000.
