### ISSUE TITLE
How to ensure that I am using a Market Order (to be executed immediately)

### ISSUE THREAD

**Issue by clemenslinders** [jjxtra/ExchangeSharp#712]
Hi,

I would like to know if I use ExchangeOrderRequest() that I am creating a market order (which should be executed immediately and not remain active in the books).

A sell order using the Binance test Api, would look like this and I would like to know is this a market order:
            this.UseWaitCursor = true;
            string marketSymbol = "BTCUSDT";

            try
            {
                var apiPreScan = CreateBinanceTestAPI();
                var ticker = await apiPreScan.Result.GetTickerAsync(marketSymbol);
                apiPreScan.Dispose();
                var api = CreateBinanceTestAPI();
                ExchangeOrderRequest request = new ExchangeOrderRequest();
                request.MarketSymbol = marketSymbol;
                request.IsBuy = false;
                request.Amount = 0.002m; //straks aantal in bezit
                request.Price = ticker.Bid;
                var placedOrder = await api.Result.PlaceOrderAsync(request);
                MessageBox.Show("Sold " + placedOrder.AmountFilled + " BTC at: " + placedOrder.AveragePrice);

                if (placedOrder.Fees != null)
                {
                    decimal paidFees = placedOrder.Fees.Value;
                }

                string feeCurrency = placedOrder.FeesCurrency;
                string clientOrderId = placedOrder.ClientOrderId;
                string orderId = placedOrder.OrderId;
                DateTime orderDate = placedOrder.OrderDate;
                api.Dispose();
            }
            catch (Exception ex)
            {
                //textTickersResult.Text = ex.ToString();
            }
            finally
            {
                Invoke(new Action(() => this.UseWaitCursor = false));
            }

If I do not set request.Price, than I get an error stating that Price cannot be null.
In this way I have to first check what the bid price is and than use that price. 

If I set Price than the actual average sell price will be different, which is to be expected.
If I set the price to 60.000 (BTC value at this time is 43.000), than it will not sell, which is fine as long as the order than is cancelled. I do not want it to go into the books and be unexpected executed like a year later.

If this is a market order and if Price is used to make sure that the price you get is within a certain margin of what you expect. Than that is OK. Just as long as an order that doesn't immediately go through gets activated at a later unexpected time.

Hope someone can help.

Kind regards,

Clemens Linders

**Comment by jjxtra** [comment]
`OrderType` should be able to specify market, are you seeing any issues there?

**Comment by clemenslinders** [comment]
Hi jjextra,

Sorry I wasn't able to reply sooner.

Thanks for your answer I added:                 
request.OrderType = ExchangeSharp.OrderType.Market;
to my code.


Kind regards,



Clemens Linders
