### ISSUE TITLE
URL to long on candle socket

### ISSUE THREAD

**Issue by jacobdeboer33** [jjxtra/ExchangeSharp#724]
Hi there.

When I try to open a candle socket with no markets specified in the parameters on Binance, the call will crash i URL longer then 2048 characters exception. Can I work around this?

System.InvalidOperationException: URL length over the limit of 2048 characters. Consider splitting instruments in multiple connections.
   at ExchangeSharp.BinanceGroup.BinanceGroupCommon.OnGetCandlesWebSocketAsync(Func`2 callbackAsync, Int32 periodSeconds, String[] marketSymbols)

Thanks,
Jacob

**Comment by jjxtra** [comment]
What is the url?

**Comment by BZ-CO** [comment]
You need to split the instruments in multiple ws connections.
It's because we subscribe for Binance data by adding instrument's names to the url.
