### ISSUE TITLE
Gdax not working for sandbox

### ISSUE THREAD

**Issue by franklin770** [jjxtra/ExchangeSharp#73]
All my calls return for placeorder and getopenorders do not work for the sandbox. They work with a different api. 

'The remote server returned an error: (400) Bad Request.'

using

public string MakeRequest(string url, string baseUrl = null, Dictionary<string, object> payload = null, string method = null)

Not sure if the error is on my side or the api  request 

Can you confirm that your Gdax methods work with the sandbox?

Thank you. (p.s. great code)

**Comment by jjxtra** [comment]
https://www.reddit.com/r/GDAX/comments/7t5ekw/sandbox_rest_api_broken/

Jeff Johnson
CEO / CTO, Digital Ruby, LLC

**Comment by franklin770** [comment]
Hi Jeff
Thanks
it seems to be working fine for async httpRequestMessage
