### ISSUE TITLE
Nonce must be greater than 1521820320325620736. You provided 636574244290423835.

### ISSUE THREAD

**Issue by espirulina** [jjxtra/ExchangeSharp#74]
I have a [BUG REPORT] 

Details:
` try
            {
                ExchangeSharp.ExchangePoloniexAPI api = new ExchangeSharp.ExchangePoloniexAPI();

                api.LoadAPIKeysUnsecure("ZZZ", "YYY");

                var results = api.GetAmounts();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }`
Error Logs (if any):
**Nonce must be greater than 1521820320325620736. You provided 636574244290423835.**

**Comment by jjxtra** [comment]
Not seeing this in my tests. Ensure latest version and that machine clock is correct.

**Comment by espirulina** [comment]
Hi, i tried last version, both ways: by NuGetPackage, and by cloning repo.
Also tried in different machines. Do you think it might be related to timezone ? Im in GMT+0. Are you in same timezone as poloniex ? Shouldn't the nonce generation be timezone independent ?
thank you

**Comment by Shutaru** [comment]
Hey guys. @jjxtra i am having the same issue! clock is right and i have latest version.

![image](https://user-images.githubusercontent.com/37865610/38019504-a13b02cc-326f-11e8-928a-606ca7c69e22.png)

**Comment by jjxtra** [comment]
Interesting the 6XX nonce is 18 chars, the 1XX nonce is 19 chars. Can
either of you pull the latest source down and put a break point on line 206
of BaseAPI.cs and tell me what it does? I am not seeing this behavior on
three machines, one on West USA, Canada and UK. The nonce always uses UTC
time.

-- Jeff
