### ISSUE TITLE
ExchangeOrderResult means different things at different exchanges. Can we standardize this?

### ISSUE THREAD

**Issue by bichuga** [jjxtra/ExchangeSharp#78]
Comparing Bittrex and Binance: 

Bittrex[Price] means the total amount in the base currency. 
Binance[Price] means price per unit (I think)

It's not clear what units the different numbers are supposed to be in. Probably different exchanges return different things. Can we get ExchangeSharp to normalize this stuff?

My suggestion:
Amount/AmountFilled are always in the market currency (e,g. ADA)
AveragePrice is price per unit in base/market. E.g. 0.000342 ETH/ADA
Fee is in the base currency
Price means... the price requested? I have no idea what this is for.

My testing:
![image](https://user-images.githubusercontent.com/9372553/38008342-018a5cf8-3203-11e8-9582-5ee635d0136c.png)

**Comment by jjxtra** [comment]
Yes this would be good to normalize. I've added similar normalization to
the candles and tickers end points. Some exchanges list the base pair
first, others second.

In my mind, price should be the limit price (most common case). For market
orders it does not apply and can probably be set to the average price. Not
all exchanges provide an average price, so for those exchanges, average
price can be set to price.

The rest of your suggestions look good. Let me know if you need guidance
implementing them.

Jeff Johnson
CEO / CTO, Digital Ruby, LLC

**Comment by jjxtra** [comment]
Pull request looked good, thanks for doing this!

**Comment by jjxtra** [comment]
We can do additional pull requests for other exchanges as needed. Binance appears to be the most picky so at least it is taken care of.
