### ISSUE TITLE
dotnet core 2 support

### ISSUE THREAD

**Issue by padmee** [jjxtra/ExchangeSharp#8]
Hello, **jjxtra**!!!
I am interested if it is possible to run and use your package on dotnet core 2.
Looks like no.
Are you plaining to make the package runnable on core?

Thanks.

**Comment by jjxtra** [comment]
Not at this time officially. Should compile though if you want to make your own project.

**Comment by jjxtra** [comment]
This is officially supported now!

**Comment by padmee** [comment]
I created an empty core 2 console app and added from nuget your lib there.
When I try to create new API oblects (ExchangeKrakenAPI api = new ExchangeKrakenAPI();), I got:

> 
> Exception has occurred: CLR/System.TypeInitializationException
> An unhandled exception of type 'System.TypeInitializationException' occurred in ExchangeSharp.dll: 'The type initializer for 'ExchangeSharp.ExchangeAPI' threw an exception.'
>  Inner exceptions found, see $exception in variables window for more details.
>  Innermost exception 	 System.NotSupportedException : The requested security protocol is not supported.
>    at System.Net.ServicePointManager.ValidateSecurityProtocol(SecurityProtocolType value)
>    at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)
>    at ExchangeSharp.BaseAPI..cctor()

Probably some libraries is not in the core package yet.. Or?

**Comment by jjxtra** [comment]
Thanks for sharing. Any chance you could pull the actual code and add the project to your solution instead of the nuget package? That might give a better breakpoint on where the failure is happening.

**Comment by jjxtra** [comment]
I fixed the problem, look for a new nuget soon. You may need to set ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls | SecurityProtocolType.Ssl3; values yourself.
