### ISSUE TITLE
Async not used correctly

### ISSUE THREAD

**Issue by NicolasDorier** [jjxtra/ExchangeSharp#93]
Hey, I am the main dev of https://github.com/btcpayserver/btcpayserver a self hosted payment server which run your own node and support multiple shitcoin on top of bitcoin.

I want to use your API to provide "auto dumping" feature to merchants.

However, it seems that you are using async incorrectly by wrapping sync call with Task.Run.

What you should do is the reverse, using async/await all along the way and use `YourMethodAsync().GetAwaiter().GetResult()` to make synchronous calls methods.

If I propose a PR fixing all of this, will you merge?

**Comment by jjxtra** [comment]
Of course, thanks for the suggestion!

Jeff Johnson
CEO / CTO, Digital Ruby, LLC

**Comment by bichuga** [comment]
Nicolas, do you have any more info about why what you propose is better?
I've seen ExchangeSharp's pattern in training videos.

**Comment by atp4al** [comment]
@bichuga  

By calling Task.Run the code becomes asynchronous so the end effect is the same. You can say that when you write "await ..." it is as if you run the code in Task.Run and then everything after the await keyword will be done after, as if you have written it in ContinueWith.

However, it is not the case under the hood as async/await generate a state machine. (you can watch the last videos of [this course](https://www.pluralsight.com/courses/asynchronous-programming-dotnet-getting-started) for a good explanation of that). The "magic" is that there is no task created, which means there will not be a thread used. As a result, async/await will scale better.

> async is good on servers because asynchronous operations scale better than threads. But if you're using Task.Run, then you're using a thread anyway.
[Source](https://stackoverflow.com/questions/13071833/is-wrapping-a-synchronous-call-in-a-task-run-to-make-it-asynchronous-beneficia?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

See [this post](https://blog.stephencleary.com/2013/11/there-is-no-thread.html) for a more detailled explanation about the fact there is no thread involved.

**Comment by jjxtra** [comment]
Still happy to merge the pull request in, read a few Microsoft blurbs about it, seems like a good idea.

**Comment by NicolasDorier** [comment]
So the issue is, if you do this way, then you are essentially blocking a thread, which is a scarse ressource. 
`Task.Run` is relying on the thread pool and if no more thread are available, even the async version would block.

And this is worse! if what is called inside `Task.Run` is also using `Task.Run` this can lead to a deadlock once no thread in the threadpool are available.

Using async/await all the way ensure that threads are freed to do other work as soon as the request is sent.

**Comment by jjxtra** [comment]
Any update on this? Might start on it myself if you haven't already...

**Comment by NicolasDorier** [comment]
I did not yet @jjxtra if you do I can review.

**Comment by jjxtra** [comment]
I've started on this, will commit soon

**Comment by jjxtra** [comment]
Progress and review can be done in async branch (pushed). I had carpal tunnel surgery last week so I am stopping for today :)

**Comment by NicolasDorier** [comment]
Nice, commented on https://github.com/jjxtra/ExchangeSharp/commit/8137391597c7d6df65267e8c5daaaeee46f8626d#r28578994

**Comment by jjxtra** [comment]
All commits are in, ready for another set of eyes

**Comment by NicolasDorier** [comment]
https://github.com/jjxtra/ExchangeSharp/compare/async#diff-0320aa165b129bc681396a8da8831dedR36 is probably not what you want.

**Comment by NicolasDorier** [comment]
I am seeing lot's of missing `.ConfigureAwait`. That said, it can be done later.
I would advise you to put the commit removing the `this.` in another PR so it is easier to review.

Except this it seems perfect. Awesome library.

**Comment by jjxtra** [comment]
Does .ConfigureAwait need to be done anywhere this is an await call?

-- Jeff

**Comment by jjxtra** [comment]
Fixed this. using anyalyzer

**Comment by jjxtra** [comment]
I made all public async methods handle the synchronization context using a helper class. Most public methods on ExchangeAPI are simply sync wrappers to a protected implementation now. That way only ExchangeAPI.cs needs to worry about the sync context. Going forward, I think this is a good pattern to follow.

Thoughts?

**Comment by jjxtra** [comment]
Are you able to perform this test? I have to move on to other projects the rest of this week.

**Comment by NicolasDorier** [comment]
will try.

**Comment by jjxtra** [comment]
Got the idea here: https://blogs.msdn.microsoft.com/benwilli/2017/02/09/an-alternative-to-configureawaitfalse-everywhere/

**Comment by NicolasDorier** [comment]
wow wonderful. I tried it and it works as adverized.

**Comment by NicolasDorier** [comment]
This w
```
 class Sync : SynchronizationContext
        {
            public override void Post(SendOrPostCallback d, object state)
            {
                throw new Exception();
                base.Post(d, state);
            }
        }
```

This cause the Exception of the SynchronizationContext (because Test continuation goes on `Sync`)
```
        [Fact]
        public async Task TestSync()
        {
            SynchronizationContext.SetSynchronizationContext(new Sync());
            await Test();
            await Task.Delay(1000);
        }

        private static async Task Test()
        {
            await new SynchronizationContextRemover();
            await Task.Delay(1000);
        }
```

This does not

```
        [Fact]
        public async Task TestSync()
        {
            SynchronizationContext.SetSynchronizationContext(new Sync());
            await new SynchronizationContextRemover();
            await Task.Delay(1000);
            await Task.Delay(1000);
        }
```

**Comment by jjxtra** [comment]
Will merge in then!

**Comment by jjxtra** [comment]
Something in the Poloniex unit tests is failing, do you have bandwidth to investigate? The dependancy injection is not working for the request maker. Haven't dug any further then that.

**Comment by jjxtra** [comment]
Never mind, the tests just need to switch to Request async, will do now and merge.

**Comment by NicolasDorier** [comment]
wait why would the tests not breaking before but break now?

**Comment by jjxtra** [comment]
NSubstitute not overriding makerequest

-- Jeff

**Comment by jjxtra** [comment]
This is merged in now to master!

**Comment by NicolasDorier** [comment]
Freaking good! Will use this in BTCPay this week. I love Bitcoin Average but I don't want all merchants complaining to me if they go down :D

**Comment by NicolasDorier** [comment]
You made a new nuget package?

**Comment by jjxtra** [comment]
Replacing my cpu cooler. Pump died after 4 months :( Will make a package
tomorrow!

-- Jeff

**Comment by NicolasDorier** [comment]
any luck? can't wait playing with your lib :D

**Comment by jjxtra** [comment]
It's out there, may take a few minutes to show up. Version 0.4.0.0
